-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local fieldnames_fieldnames_pb_desc = require "fieldnames.fieldnames_pb_desc"

local fieldnames_fieldnames_pb = {}

---@class fieldnames_fieldnames_pb.Message.OneofMessageConflict : protobuf.Message

---@class fieldnames_fieldnames_pb.Message : protobuf.Message
---@field field_one string
---@field FieldTwo string
---@field fieldThree string
---@field field__four string
---@field descriptor string
---@field marshal string
---@field unmarshal string
---@field proto_message string
---@field CamelCase string
---@field CamelCase_ string
---@field camel_case string
---@field CamelCase__ string
---@field get_name string
---@field name string
---@field OneofConflictA string
---@field oneof_no_conflict string
---@field OneofConflictB string
---@field oneof_message_conflict string

---@type fun():fieldnames_fieldnames_pb.Message.OneofMessageConflict
fieldnames_fieldnames_pb.Message.OneofMessageConflict = protobuf.Message(fieldnames_fieldnames_pb_desc.message_type[1].nested_type[1])
fieldnames_fieldnames_pb.Message.OneofMessageConflict._FullName = ".goproto.protoc.fieldnames.Message.OneofMessageConflict"
fieldnames_fieldnames_pb.Message.OneofMessageConflict._Descriptor = "fieldnames_fieldnames_pb_desc.message_type[1].nested_type[1]"
registry.RegistMessage(".goproto.protoc.fieldnames.Message.OneofMessageConflict", fieldnames_fieldnames_pb.Message.OneofMessageConflict)

---@type fun():fieldnames_fieldnames_pb.Message
fieldnames_fieldnames_pb.Message = protobuf.Message(fieldnames_fieldnames_pb_desc.message_type[1])
fieldnames_fieldnames_pb.Message._FullName = ".goproto.protoc.fieldnames.Message"
fieldnames_fieldnames_pb.Message._Descriptor = "fieldnames_fieldnames_pb_desc.message_type[1]"
registry.RegistMessage(".goproto.protoc.fieldnames.Message", fieldnames_fieldnames_pb.Message)


return fieldnames_fieldnames_pb
