-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local imports_test_a_2_m3_pb_desc = require "imports.test_a_2.m3_pb_desc"

local imports_test_a_2_m3_pb = {}

---@class imports_test_a_2_m3_pb.M3

---@type fun():imports_test_a_2_m3_pb.M3 @New a '.test.a.M3'
imports_test_a_2_m3_pb.M3 = protobuf_reflect.Message(imports_test_a_2_m3_pb_desc.message_type[1])


return imports_test_a_2_m3_pb
