-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local imports_test_a_2_m3_pb_desc = require "imports.test_a_2.m3_pb_desc"

local imports_test_a_2_m3_pb = {}

---@class imports_test_a_2_m3_pb.M3 : protobuf.Message

---@type fun():imports_test_a_2_m3_pb.M3
imports_test_a_2_m3_pb.M3 = protobuf.Message(imports_test_a_2_m3_pb_desc.message_type[1])
imports_test_a_2_m3_pb.M3._FullName = ".test.a.M3"
imports_test_a_2_m3_pb.M3._Descriptor = "imports_test_a_2_m3_pb_desc.message_type[1]"
registry.RegistMessage(".test.a.M3", imports_test_a_2_m3_pb.M3)


return imports_test_a_2_m3_pb
