-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
return {
    name = [[imports/test_a_2/m4.proto]],
    package = [[test.a]],
    message_type = {
        {
            name = [[M4]],
        },
    },
    options = {
        go_package = [[google.golang.org/protobuf/cmd/protoc-gen-go/testdata/imports/test_a_2]],
    },
    syntax = [[proto3]],
}