-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local imports_test_a_2_m4_pb_desc = require "imports.test_a_2.m4_pb_desc"

local imports_test_a_2_m4_pb = {}

---@class imports_test_a_2_m4_pb.M4 : protobuf.Message

---@type fun():imports_test_a_2_m4_pb.M4
imports_test_a_2_m4_pb.M4 = protobuf.Message(imports_test_a_2_m4_pb_desc.message_type[1])
imports_test_a_2_m4_pb.M4._FullName = ".test.a.M4"
imports_test_a_2_m4_pb.M4._Descriptor = "imports_test_a_2_m4_pb_desc.message_type[1]"
registry.RegistMessage(imports_test_a_2_m4_pb.M4)


return imports_test_a_2_m4_pb
