-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

return {
    name = [[extensions/extra/extra.proto]],
    package = [[goproto.protoc.extension.extra]],
    message_type = {
        {
            name = [[ExtraMessage]],
            field = {
                {
                    name = [[data]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_BYTES]],
                    json_name = [[data]],
                },
            },
        },
    },
    options = {
        go_package = [[google.golang.org/protobuf/cmd/protoc-gen-go/testdata/extensions/extra]],
    },
}