-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local extensions_extra_extra_pb_desc = require "extensions.extra.extra_pb_desc"

local extensions_extra_extra_pb = {}

---@class extensions_extra_extra_pb.ExtraMessage : protobuf.Message
---@field data string

---@type fun():extensions_extra_extra_pb.ExtraMessage
extensions_extra_extra_pb.ExtraMessage = protobuf.Message(extensions_extra_extra_pb_desc.message_type[1])
extensions_extra_extra_pb.ExtraMessage._FullName = ".goproto.protoc.extension.extra.ExtraMessage"
extensions_extra_extra_pb.ExtraMessage._Descriptor = "extensions_extra_extra_pb_desc.message_type[1]"
registry.RegistMessage(".goproto.protoc.extension.extra.ExtraMessage", extensions_extra_extra_pb.ExtraMessage)


return extensions_extra_extra_pb
