-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local extensions_extra_extra_pb_desc = require "extensions.extra.extra_pb_desc"

local extensions_extra_extra_pb = {}

---@class extensions_extra_extra_pb.ExtraMessage
---@field data string

---@type fun():extensions_extra_extra_pb.ExtraMessage @New a '.goproto.protoc.extension.extra.ExtraMessage'
extensions_extra_extra_pb.ExtraMessage = protobuf_reflect.Message(extensions_extra_extra_pb_desc.message_type[1])


return extensions_extra_extra_pb
