-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
return {
    name = [[proto3/enum.proto]],
    package = [[goproto.protoc.proto3]],
    enum_type = {
        {
            name = [[Enum]],
            value = {
                {
                    name = [[ZERO]],
                    number = 0,
                },
                {
                    name = [[ONE]],
                    number = 1,
                },
                {
                    name = [[TWO]],
                    number = 2,
                },
            },
        },
    },
    options = {
        go_package = [[google.golang.org/protobuf/cmd/protoc-gen-go/testdata/proto3]],
    },
    syntax = [[proto3]],
}