-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local proto3_enum_pb_desc = require "proto3.enum_pb_desc"

local proto3_enum_pb = {}

---@alias proto3_enum_pb.Enum
---| 'proto3_enum_pb.Enum.ZERO' # = 0
---| 'proto3_enum_pb.Enum.ONE' # = 1
---| 'proto3_enum_pb.Enum.TWO' # = 2

proto3_enum_pb.Enum = protobuf_reflect.Enum(proto3_enum_pb_desc.enum_type[1])
proto3_enum_pb.Enum.ZERO = 0
proto3_enum_pb.Enum.ONE = 1
proto3_enum_pb.Enum.TWO = 2


return proto3_enum_pb
