-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local proto3_enum_pb_desc = require "proto3.enum_pb_desc"

local proto3_enum_pb = {}

---@alias proto3_enum_pb.Enum
---| 'proto3_enum_pb.Enum.ZERO' # = 0
---| 'proto3_enum_pb.Enum.ONE' # = 1
---| 'proto3_enum_pb.Enum.TWO' # = 2

proto3_enum_pb.Enum = {}
proto3_enum_pb.Enum._FullName = ".goproto.protoc.proto3.Enum"
proto3_enum_pb.Enum._Descriptor = "proto3_enum_pb_desc.enum_type[1]"
proto3_enum_pb.Enum.ZERO = 0
proto3_enum_pb.Enum.ONE = 1
proto3_enum_pb.Enum.TWO = 2
proto3_enum_pb.Enum[0] = ".goproto.protoc.proto3.Enum.ZERO"
proto3_enum_pb.Enum[1] = ".goproto.protoc.proto3.Enum.ONE"
proto3_enum_pb.Enum[2] = ".goproto.protoc.proto3.Enum.TWO"
registry.RegistEnum(proto3_enum_pb.Enum)


return proto3_enum_pb
