-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local proto3_fields_pb_desc = require "proto3.fields_pb_desc"

local proto3_fields_pb = {}

---@alias proto3_fields_pb.FieldTestMessage.Enum
---| 'proto3_fields_pb.FieldTestMessage.Enum.ZERO' # = 0

---@class proto3_fields_pb.FieldTestMessage.MapInt32Int64Entry : protobuf.Message
---@field key number
---@field value number

---@class proto3_fields_pb.FieldTestMessage.MapStringMessageEntry : protobuf.Message
---@field key string
---@field value proto3_fields_pb.FieldTestMessage.Message

---@class proto3_fields_pb.FieldTestMessage.MapFixed64EnumEntry : protobuf.Message
---@field key number
---@field value proto3_fields_pb.FieldTestMessage.Enum

---@class proto3_fields_pb.FieldTestMessage.Message : protobuf.Message

---@class proto3_fields_pb.FieldTestMessage : protobuf.Message
---@field optional_bool string
---@field optional_enum proto3_fields_pb.FieldTestMessage.Enum
---@field optional_int32 number
---@field optional_sint32 number
---@field optional_uint32 number
---@field optional_int64 number
---@field optional_sint64 number
---@field optional_uint64 number
---@field optional_sfixed32 number
---@field optional_fixed32 number
---@field optional_float number
---@field optional_sfixed64 number
---@field optional_fixed64 number
---@field optional_double number
---@field optional_string string
---@field optional_bytes string
---@field optional_Message proto3_fields_pb.FieldTestMessage.Message
---@field repeated_bool boolean[]
---@field repeated_enum proto3_fields_pb.FieldTestMessage.Enum[]
---@field repeated_int32 number[]
---@field repeated_sint32 number[]
---@field repeated_uint32 number[]
---@field repeated_int64 number[]
---@field repeated_sint64 number[]
---@field repeated_uint64 number[]
---@field repeated_sfixed32 number[]
---@field repeated_fixed32 number[]
---@field repeated_float number[]
---@field repeated_sfixed64 number[]
---@field repeated_fixed64 number[]
---@field repeated_double number[]
---@field repeated_string string[]
---@field repeated_bytes string[]
---@field repeated_Message proto3_fields_pb.FieldTestMessage.Message[]
---@field map_int32_int64 dict<number, number>
---@field map_string_message dict<string, proto3_fields_pb.FieldTestMessage.Message>
---@field map_fixed64_enum dict<number, proto3_fields_pb.FieldTestMessage.Enum>

proto3_fields_pb.FieldTestMessage.Enum = {}
proto3_fields_pb.FieldTestMessage.Enum._FullName = ".goproto.protoc.proto3.FieldTestMessage.Enum"
proto3_fields_pb.FieldTestMessage.Enum._Descriptor = "proto3_fields_pb_desc.message_type[1].enum_type[1]"
proto3_fields_pb.FieldTestMessage.Enum.ZERO = 0
proto3_fields_pb.FieldTestMessage.Enum[0] = ".goproto.protoc.proto3.FieldTestMessage.Enum.ZERO"
registry.RegistEnum(proto3_fields_pb.FieldTestMessage.Enum)

---@type fun():proto3_fields_pb.FieldTestMessage.MapInt32Int64Entry
proto3_fields_pb.FieldTestMessage.MapInt32Int64Entry = protobuf.Message(proto3_fields_pb_desc.message_type[1].nested_type[1])
proto3_fields_pb.FieldTestMessage.MapInt32Int64Entry._FullName = ".goproto.protoc.proto3.FieldTestMessage.MapInt32Int64Entry"
proto3_fields_pb.FieldTestMessage.MapInt32Int64Entry._Descriptor = "proto3_fields_pb_desc.message_type[1].nested_type[1]"
registry.RegistMessage(proto3_fields_pb.FieldTestMessage.MapInt32Int64Entry)

---@type fun():proto3_fields_pb.FieldTestMessage.MapStringMessageEntry
proto3_fields_pb.FieldTestMessage.MapStringMessageEntry = protobuf.Message(proto3_fields_pb_desc.message_type[1].nested_type[2])
proto3_fields_pb.FieldTestMessage.MapStringMessageEntry._FullName = ".goproto.protoc.proto3.FieldTestMessage.MapStringMessageEntry"
proto3_fields_pb.FieldTestMessage.MapStringMessageEntry._Descriptor = "proto3_fields_pb_desc.message_type[1].nested_type[2]"
registry.RegistMessage(proto3_fields_pb.FieldTestMessage.MapStringMessageEntry)

---@type fun():proto3_fields_pb.FieldTestMessage.MapFixed64EnumEntry
proto3_fields_pb.FieldTestMessage.MapFixed64EnumEntry = protobuf.Message(proto3_fields_pb_desc.message_type[1].nested_type[3])
proto3_fields_pb.FieldTestMessage.MapFixed64EnumEntry._FullName = ".goproto.protoc.proto3.FieldTestMessage.MapFixed64EnumEntry"
proto3_fields_pb.FieldTestMessage.MapFixed64EnumEntry._Descriptor = "proto3_fields_pb_desc.message_type[1].nested_type[3]"
registry.RegistMessage(proto3_fields_pb.FieldTestMessage.MapFixed64EnumEntry)

---@type fun():proto3_fields_pb.FieldTestMessage.Message
proto3_fields_pb.FieldTestMessage.Message = protobuf.Message(proto3_fields_pb_desc.message_type[1].nested_type[4])
proto3_fields_pb.FieldTestMessage.Message._FullName = ".goproto.protoc.proto3.FieldTestMessage.Message"
proto3_fields_pb.FieldTestMessage.Message._Descriptor = "proto3_fields_pb_desc.message_type[1].nested_type[4]"
registry.RegistMessage(proto3_fields_pb.FieldTestMessage.Message)

---@type fun():proto3_fields_pb.FieldTestMessage
proto3_fields_pb.FieldTestMessage = protobuf.Message(proto3_fields_pb_desc.message_type[1])
proto3_fields_pb.FieldTestMessage._FullName = ".goproto.protoc.proto3.FieldTestMessage"
proto3_fields_pb.FieldTestMessage._Descriptor = "proto3_fields_pb_desc.message_type[1]"
registry.RegistMessage(proto3_fields_pb.FieldTestMessage)


return proto3_fields_pb
