-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local proto3_fields_pb_desc = require "proto3.fields_pb_desc"

local proto3_fields_pb = {}

---@alias proto3_fields_pb.FieldTestMessage.Enum
---| 'proto3_fields_pb.FieldTestMessage.Enum.ZERO' # = 0

---@class proto3_fields_pb.FieldTestMessage.MapInt32Int64Entry
---@field key number
---@field value number

---@class proto3_fields_pb.FieldTestMessage.MapStringMessageEntry
---@field key string
---@field value proto3_fields_pb.FieldTestMessage.Message

---@class proto3_fields_pb.FieldTestMessage.MapFixed64EnumEntry
---@field key number
---@field value proto3_fields_pb.FieldTestMessage.Enum

---@class proto3_fields_pb.FieldTestMessage.Message

---@class proto3_fields_pb.FieldTestMessage
---@field optional_bool string
---@field optional_enum proto3_fields_pb.FieldTestMessage.Enum
---@field optional_int32 number
---@field optional_sint32 number
---@field optional_uint32 number
---@field optional_int64 number
---@field optional_sint64 number
---@field optional_uint64 number
---@field optional_sfixed32 number
---@field optional_fixed32 number
---@field optional_float number
---@field optional_sfixed64 number
---@field optional_fixed64 number
---@field optional_double number
---@field optional_string string
---@field optional_bytes string
---@field optional_Message proto3_fields_pb.FieldTestMessage.Message
---@field repeated_bool boolean[]
---@field repeated_enum proto3_fields_pb.FieldTestMessage.Enum[]
---@field repeated_int32 number[]
---@field repeated_sint32 number[]
---@field repeated_uint32 number[]
---@field repeated_int64 number[]
---@field repeated_sint64 number[]
---@field repeated_uint64 number[]
---@field repeated_sfixed32 number[]
---@field repeated_fixed32 number[]
---@field repeated_float number[]
---@field repeated_sfixed64 number[]
---@field repeated_fixed64 number[]
---@field repeated_double number[]
---@field repeated_string string[]
---@field repeated_bytes string[]
---@field repeated_Message proto3_fields_pb.FieldTestMessage.Message[]
---@field map_int32_int64 proto3_fields_pb.FieldTestMessage.MapInt32Int64Entry[]
---@field map_string_message proto3_fields_pb.FieldTestMessage.MapStringMessageEntry[]
---@field map_fixed64_enum proto3_fields_pb.FieldTestMessage.MapFixed64EnumEntry[]

proto3_fields_pb.FieldTestMessage.Enum = protobuf_reflect.Enum(proto3_fields_pb_desc.message_type[1].enum_type[1])
proto3_fields_pb.FieldTestMessage.Enum.ZERO = 0

---@type fun():proto3_fields_pb.FieldTestMessage.MapInt32Int64Entry @New a '.goproto.protoc.proto3.FieldTestMessage.MapInt32Int64Entry'
proto3_fields_pb.FieldTestMessage.MapInt32Int64Entry = protobuf_reflect.Message(proto3_fields_pb_desc.message_type[1].nested_type[1])

---@type fun():proto3_fields_pb.FieldTestMessage.MapStringMessageEntry @New a '.goproto.protoc.proto3.FieldTestMessage.MapStringMessageEntry'
proto3_fields_pb.FieldTestMessage.MapStringMessageEntry = protobuf_reflect.Message(proto3_fields_pb_desc.message_type[1].nested_type[2])

---@type fun():proto3_fields_pb.FieldTestMessage.MapFixed64EnumEntry @New a '.goproto.protoc.proto3.FieldTestMessage.MapFixed64EnumEntry'
proto3_fields_pb.FieldTestMessage.MapFixed64EnumEntry = protobuf_reflect.Message(proto3_fields_pb_desc.message_type[1].nested_type[3])

---@type fun():proto3_fields_pb.FieldTestMessage.Message @New a '.goproto.protoc.proto3.FieldTestMessage.Message'
proto3_fields_pb.FieldTestMessage.Message = protobuf_reflect.Message(proto3_fields_pb_desc.message_type[1].nested_type[4])

---@type fun():proto3_fields_pb.FieldTestMessage @New a '.goproto.protoc.proto3.FieldTestMessage'
proto3_fields_pb.FieldTestMessage = protobuf_reflect.Message(proto3_fields_pb_desc.message_type[1])


return proto3_fields_pb
