-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local proto2_enum_pb_desc = require "proto2.enum_pb_desc"

local proto2_enum_pb = {}

---@alias proto2_enum_pb.EnumType1
---| 'proto2_enum_pb.EnumType1.ONE' # = 1
---| 'proto2_enum_pb.EnumType1.TWO' # = 2

---@alias proto2_enum_pb.EnumType2
---| 'proto2_enum_pb.EnumType2.duplicate1' # = 1
---| 'proto2_enum_pb.EnumType2.duplicate2' # = 1

---@alias proto2_enum_pb.EnumContainerMessage1.NestedEnumType1A
---| 'proto2_enum_pb.EnumContainerMessage1.NestedEnumType1A.NESTED_1A_VALUE' # = 0

---@alias proto2_enum_pb.EnumContainerMessage1.NestedEnumType1B
---| 'proto2_enum_pb.EnumContainerMessage1.NestedEnumType1B.NESTED_1B_VALUE' # = 0

---@alias proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2A
---| 'proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2A.NESTED_2A_VALUE' # = 0

---@alias proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2B
---| 'proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2B.NESTED_2B_VALUE' # = 0

---@class proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2 : protobuf.Message

---@class proto2_enum_pb.EnumContainerMessage1 : protobuf.Message
---@field default_duplicate1 proto2_enum_pb.EnumType2
---@field default_duplicate2 proto2_enum_pb.EnumType2

proto2_enum_pb.EnumType1 = {}
proto2_enum_pb.EnumType1._FullName = ".goproto.protoc.proto2.EnumType1"
proto2_enum_pb.EnumType1._Descriptor = "proto2_enum_pb_desc.enum_type[1]"
registry.RegistEnum(".goproto.protoc.proto2.EnumType1", proto2_enum_pb.EnumType1)
proto2_enum_pb.EnumType1.ONE = 1
proto2_enum_pb.EnumType1.TWO = 2
proto2_enum_pb.EnumType1[1] = ".goproto.protoc.proto2.EnumType1.ONE"
proto2_enum_pb.EnumType1[2] = ".goproto.protoc.proto2.EnumType1.TWO"

proto2_enum_pb.EnumType2 = {}
proto2_enum_pb.EnumType2._FullName = ".goproto.protoc.proto2.EnumType2"
proto2_enum_pb.EnumType2._Descriptor = "proto2_enum_pb_desc.enum_type[2]"
registry.RegistEnum(".goproto.protoc.proto2.EnumType2", proto2_enum_pb.EnumType2)
proto2_enum_pb.EnumType2.duplicate1 = 1
proto2_enum_pb.EnumType2.duplicate2 = 1
proto2_enum_pb.EnumType2[1] = ".goproto.protoc.proto2.EnumType2.duplicate1"
proto2_enum_pb.EnumType2[1] = ".goproto.protoc.proto2.EnumType2.duplicate2"

proto2_enum_pb.EnumContainerMessage1.NestedEnumType1A = {}
proto2_enum_pb.EnumContainerMessage1.NestedEnumType1A._FullName = ".goproto.protoc.proto2.EnumContainerMessage1.NestedEnumType1A"
proto2_enum_pb.EnumContainerMessage1.NestedEnumType1A._Descriptor = "proto2_enum_pb_desc.message_type[1].enum_type[1]"
registry.RegistEnum(".goproto.protoc.proto2.EnumContainerMessage1.NestedEnumType1A", proto2_enum_pb.EnumContainerMessage1.NestedEnumType1A)
proto2_enum_pb.EnumContainerMessage1.NestedEnumType1A.NESTED_1A_VALUE = 0
proto2_enum_pb.EnumContainerMessage1.NestedEnumType1A[0] = ".goproto.protoc.proto2.EnumContainerMessage1.NestedEnumType1A.NESTED_1A_VALUE"

proto2_enum_pb.EnumContainerMessage1.NestedEnumType1B = {}
proto2_enum_pb.EnumContainerMessage1.NestedEnumType1B._FullName = ".goproto.protoc.proto2.EnumContainerMessage1.NestedEnumType1B"
proto2_enum_pb.EnumContainerMessage1.NestedEnumType1B._Descriptor = "proto2_enum_pb_desc.message_type[1].enum_type[2]"
registry.RegistEnum(".goproto.protoc.proto2.EnumContainerMessage1.NestedEnumType1B", proto2_enum_pb.EnumContainerMessage1.NestedEnumType1B)
proto2_enum_pb.EnumContainerMessage1.NestedEnumType1B.NESTED_1B_VALUE = 0
proto2_enum_pb.EnumContainerMessage1.NestedEnumType1B[0] = ".goproto.protoc.proto2.EnumContainerMessage1.NestedEnumType1B.NESTED_1B_VALUE"

proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2A = {}
proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2A._FullName = ".goproto.protoc.proto2.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2A"
proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2A._Descriptor = "proto2_enum_pb_desc.message_type[1].nested_type[1].enum_type[1]"
registry.RegistEnum(".goproto.protoc.proto2.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2A", proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2A)
proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2A.NESTED_2A_VALUE = 0
proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2A[0] = ".goproto.protoc.proto2.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2A.NESTED_2A_VALUE"

proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2B = {}
proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2B._FullName = ".goproto.protoc.proto2.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2B"
proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2B._Descriptor = "proto2_enum_pb_desc.message_type[1].nested_type[1].enum_type[2]"
registry.RegistEnum(".goproto.protoc.proto2.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2B", proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2B)
proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2B.NESTED_2B_VALUE = 0
proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2B[0] = ".goproto.protoc.proto2.EnumContainerMessage1.EnumContainerMessage2.NestedEnumType2B.NESTED_2B_VALUE"

---@type fun():proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2
proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2 = protobuf.Message(proto2_enum_pb_desc.message_type[1].nested_type[1])
proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2._FullName = ".goproto.protoc.proto2.EnumContainerMessage1.EnumContainerMessage2"
proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2._Descriptor = "proto2_enum_pb_desc.message_type[1].nested_type[1]"
registry.RegistMessage(".goproto.protoc.proto2.EnumContainerMessage1.EnumContainerMessage2", proto2_enum_pb.EnumContainerMessage1.EnumContainerMessage2)

---@type fun():proto2_enum_pb.EnumContainerMessage1
proto2_enum_pb.EnumContainerMessage1 = protobuf.Message(proto2_enum_pb_desc.message_type[1])
proto2_enum_pb.EnumContainerMessage1._FullName = ".goproto.protoc.proto2.EnumContainerMessage1"
proto2_enum_pb.EnumContainerMessage1._Descriptor = "proto2_enum_pb_desc.message_type[1]"
registry.RegistMessage(".goproto.protoc.proto2.EnumContainerMessage1", proto2_enum_pb.EnumContainerMessage1)


return proto2_enum_pb
