-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

return {
    name = [[proto2/enum.proto]],
    package = [[goproto.protoc.proto2]],
    message_type = {
        {
            name = [[EnumContainerMessage1]],
            field = {
                {
                    name = [[default_duplicate1]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_ENUM]],
                    type_name = [[.goproto.protoc.proto2.EnumType2]],
                    default_value = [[duplicate1]],
                    json_name = [[defaultDuplicate1]],
                },
                {
                    name = [[default_duplicate2]],
                    number = 2,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_ENUM]],
                    type_name = [[.goproto.protoc.proto2.EnumType2]],
                    default_value = [[duplicate2]],
                    json_name = [[defaultDuplicate2]],
                },
            },
            nested_type = {
                {
                    name = [[EnumContainerMessage2]],
                    enum_type = {
                        {
                            name = [[NestedEnumType2A]],
                            value = {
                                {
                                    name = [[NESTED_2A_VALUE]],
                                    number = 0,
                                },
                            },
                        },
                        {
                            name = [[NestedEnumType2B]],
                            value = {
                                {
                                    name = [[NESTED_2B_VALUE]],
                                    number = 0,
                                },
                            },
                        },
                    },
                },
            },
            enum_type = {
                {
                    name = [[NestedEnumType1A]],
                    value = {
                        {
                            name = [[NESTED_1A_VALUE]],
                            number = 0,
                        },
                    },
                },
                {
                    name = [[NestedEnumType1B]],
                    value = {
                        {
                            name = [[NESTED_1B_VALUE]],
                            number = 0,
                        },
                    },
                },
            },
        },
    },
    enum_type = {
        {
            name = [[EnumType1]],
            value = {
                {
                    name = [[ONE]],
                    number = 1,
                },
                {
                    name = [[TWO]],
                    number = 2,
                },
            },
        },
        {
            name = [[EnumType2]],
            value = {
                {
                    name = [[duplicate1]],
                    number = 1,
                },
                {
                    name = [[duplicate2]],
                    number = 1,
                },
            },
            options = {
                allow_alias = true,
            },
            reserved_range = {
                {
                    start = 2,
                    end_ = 2,
                },
                {
                    start = 3,
                    end_ = 3,
                },
            },
            reserved_name = {
                [[RESERVED1]],
                [[RESERVED2]],
            },
        },
    },
    options = {
        go_package = [[google.golang.org/protobuf/cmd/protoc-gen-go/testdata/proto2]],
    },
}