-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local proto2_fields_pb_desc = require "proto2.fields_pb_desc"

local proto2_fields_pb = {}

---@alias proto2_fields_pb.FieldTestMessage.Enum
---| 'proto2_fields_pb.FieldTestMessage.Enum.ZERO' # = 0
---| 'proto2_fields_pb.FieldTestMessage.Enum.ONE' # = 1

---@class proto2_fields_pb.FieldTestMessage.OptionalGroup
---@field optional_group string

---@class proto2_fields_pb.FieldTestMessage.RequiredGroup
---@field required_group string

---@class proto2_fields_pb.FieldTestMessage.RepeatedGroup
---@field repeated_group string[]

---@class proto2_fields_pb.FieldTestMessage.MapInt32Int64Entry
---@field key number
---@field value number

---@class proto2_fields_pb.FieldTestMessage.MapStringMessageEntry
---@field key string
---@field value proto2_fields_pb.FieldTestMessage.Message

---@class proto2_fields_pb.FieldTestMessage.MapFixed64EnumEntry
---@field key number
---@field value proto2_fields_pb.FieldTestMessage.Enum

---@class proto2_fields_pb.FieldTestMessage.OneofGroup
---@field oneof_group_field string

---@class proto2_fields_pb.FieldTestMessage.Message

---@class proto2_fields_pb.FieldTestMessage
---@field optional_bool boolean
---@field optional_enum proto2_fields_pb.FieldTestMessage.Enum
---@field optional_int32 number
---@field optional_sint32 number
---@field optional_uint32 number
---@field optional_int64 number
---@field optional_sint64 number
---@field optional_uint64 number
---@field optional_sfixed32 number
---@field optional_fixed32 number
---@field optional_float number
---@field optional_sfixed64 number
---@field optional_fixed64 number
---@field optional_double number
---@field optional_string string
---@field optional_bytes string
---@field optional_Message proto2_fields_pb.FieldTestMessage.Message
---@field optionalgroup proto2_fields_pb.FieldTestMessage.OptionalGroup
---@field required_bool boolean
---@field required_enum proto2_fields_pb.FieldTestMessage.Enum
---@field required_int32 number
---@field required_sint32 number
---@field required_uint32 number
---@field required_int64 number
---@field required_sint64 number
---@field required_uint64 number
---@field required_sfixed32 number
---@field required_fixed32 number
---@field required_float number
---@field required_sfixed64 number
---@field required_fixed64 number
---@field required_double number
---@field required_string string
---@field required_bytes string
---@field required_Message proto2_fields_pb.FieldTestMessage.Message
---@field requiredgroup proto2_fields_pb.FieldTestMessage.RequiredGroup
---@field repeated_bool boolean[]
---@field repeated_enum proto2_fields_pb.FieldTestMessage.Enum[]
---@field repeated_int32 number[]
---@field repeated_sint32 number[]
---@field repeated_uint32 number[]
---@field repeated_int64 number[]
---@field repeated_sint64 number[]
---@field repeated_uint64 number[]
---@field repeated_sfixed32 number[]
---@field repeated_fixed32 number[]
---@field repeated_float number[]
---@field repeated_sfixed64 number[]
---@field repeated_fixed64 number[]
---@field repeated_double number[]
---@field repeated_string string[]
---@field repeated_bytes string[]
---@field repeated_Message proto2_fields_pb.FieldTestMessage.Message[]
---@field repeatedgroup proto2_fields_pb.FieldTestMessage.RepeatedGroup[]
---@field default_bool boolean
---@field default_enum proto2_fields_pb.FieldTestMessage.Enum
---@field default_int32 number
---@field default_sint32 number
---@field default_uint32 number
---@field default_int64 number
---@field default_sint64 number
---@field default_uint64 number
---@field default_sfixed32 number
---@field default_fixed32 number
---@field default_float number
---@field default_sfixed64 number
---@field default_fixed64 number
---@field default_double number
---@field default_string string
---@field default_bytes string
---@field default_zero_string string
---@field default_zero_bytes string
---@field default_float_neginf number
---@field default_float_posinf number
---@field default_float_nan number
---@field default_double_neginf number
---@field default_double_posinf number
---@field default_double_nan number
---@field map_int32_int64 proto2_fields_pb.FieldTestMessage.MapInt32Int64Entry[]
---@field map_string_message proto2_fields_pb.FieldTestMessage.MapStringMessageEntry[]
---@field map_fixed64_enum proto2_fields_pb.FieldTestMessage.MapFixed64EnumEntry[]
---@field oneof_bool boolean
---@field oneof_enum proto2_fields_pb.FieldTestMessage.Enum
---@field oneof_int32 number
---@field oneof_sint32 number
---@field oneof_uint32 number
---@field oneof_int64 number
---@field oneof_sint64 number
---@field oneof_uint64 number
---@field oneof_sfixed32 number
---@field oneof_fixed32 number
---@field oneof_float number
---@field oneof_sfixed64 number
---@field oneof_fixed64 number
---@field oneof_double number
---@field oneof_string string
---@field oneof_bytes string
---@field oneof_Message proto2_fields_pb.FieldTestMessage.Message
---@field oneofgroup proto2_fields_pb.FieldTestMessage.OneofGroup
---@field oneof_largest_tag number
---@field oneof_two_1 number
---@field oneof_two_2 number

proto2_fields_pb.FieldTestMessage.Enum = protobuf_reflect.Enum(proto2_fields_pb_desc.message_type[1].enum_type[1])
proto2_fields_pb.FieldTestMessage.Enum.ZERO = 0
proto2_fields_pb.FieldTestMessage.Enum.ONE = 1

---@type fun():proto2_fields_pb.FieldTestMessage.OptionalGroup @New a '.goproto.protoc.proto2.FieldTestMessage.OptionalGroup'
proto2_fields_pb.FieldTestMessage.OptionalGroup = protobuf_reflect.Message(proto2_fields_pb_desc.message_type[1].nested_type[1])

---@type fun():proto2_fields_pb.FieldTestMessage.RequiredGroup @New a '.goproto.protoc.proto2.FieldTestMessage.RequiredGroup'
proto2_fields_pb.FieldTestMessage.RequiredGroup = protobuf_reflect.Message(proto2_fields_pb_desc.message_type[1].nested_type[2])

---@type fun():proto2_fields_pb.FieldTestMessage.RepeatedGroup @New a '.goproto.protoc.proto2.FieldTestMessage.RepeatedGroup'
proto2_fields_pb.FieldTestMessage.RepeatedGroup = protobuf_reflect.Message(proto2_fields_pb_desc.message_type[1].nested_type[3])

---@type fun():proto2_fields_pb.FieldTestMessage.MapInt32Int64Entry @New a '.goproto.protoc.proto2.FieldTestMessage.MapInt32Int64Entry'
proto2_fields_pb.FieldTestMessage.MapInt32Int64Entry = protobuf_reflect.Message(proto2_fields_pb_desc.message_type[1].nested_type[4])

---@type fun():proto2_fields_pb.FieldTestMessage.MapStringMessageEntry @New a '.goproto.protoc.proto2.FieldTestMessage.MapStringMessageEntry'
proto2_fields_pb.FieldTestMessage.MapStringMessageEntry = protobuf_reflect.Message(proto2_fields_pb_desc.message_type[1].nested_type[5])

---@type fun():proto2_fields_pb.FieldTestMessage.MapFixed64EnumEntry @New a '.goproto.protoc.proto2.FieldTestMessage.MapFixed64EnumEntry'
proto2_fields_pb.FieldTestMessage.MapFixed64EnumEntry = protobuf_reflect.Message(proto2_fields_pb_desc.message_type[1].nested_type[6])

---@type fun():proto2_fields_pb.FieldTestMessage.OneofGroup @New a '.goproto.protoc.proto2.FieldTestMessage.OneofGroup'
proto2_fields_pb.FieldTestMessage.OneofGroup = protobuf_reflect.Message(proto2_fields_pb_desc.message_type[1].nested_type[7])

---@type fun():proto2_fields_pb.FieldTestMessage.Message @New a '.goproto.protoc.proto2.FieldTestMessage.Message'
proto2_fields_pb.FieldTestMessage.Message = protobuf_reflect.Message(proto2_fields_pb_desc.message_type[1].nested_type[8])

---@type fun():proto2_fields_pb.FieldTestMessage @New a '.goproto.protoc.proto2.FieldTestMessage'
proto2_fields_pb.FieldTestMessage = protobuf_reflect.Message(proto2_fields_pb_desc.message_type[1])


return proto2_fields_pb
