-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local proto2_nested_messages_pb_desc = require "proto2.nested_messages_pb_desc"

local proto2_nested_messages_pb = {}

---@class proto2_nested_messages_pb.Layer1.Layer2.Layer3

---@class proto2_nested_messages_pb.Layer1.Layer2
---@field l3 proto2_nested_messages_pb.Layer1.Layer2.Layer3

---@class proto2_nested_messages_pb.Layer1
---@field l2 proto2_nested_messages_pb.Layer1.Layer2
---@field l3 proto2_nested_messages_pb.Layer1.Layer2.Layer3

---@type fun():proto2_nested_messages_pb.Layer1.Layer2.Layer3 @New a '.goproto.protoc.proto2.Layer1.Layer2.Layer3'
proto2_nested_messages_pb.Layer1.Layer2.Layer3 = protobuf_reflect.Message(proto2_nested_messages_pb_desc.message_type[1].nested_type[1].nested_type[1])

---@type fun():proto2_nested_messages_pb.Layer1.Layer2 @New a '.goproto.protoc.proto2.Layer1.Layer2'
proto2_nested_messages_pb.Layer1.Layer2 = protobuf_reflect.Message(proto2_nested_messages_pb_desc.message_type[1].nested_type[1])

---@type fun():proto2_nested_messages_pb.Layer1 @New a '.goproto.protoc.proto2.Layer1'
proto2_nested_messages_pb.Layer1 = protobuf_reflect.Message(proto2_nested_messages_pb_desc.message_type[1])


return proto2_nested_messages_pb
