-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

return {
    name = [[proto2/nested_messages.proto]],
    package = [[goproto.protoc.proto2]],
    message_type = {
        {
            name = [[Layer1]],
            field = {
                {
                    name = [[l2]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_MESSAGE]],
                    type_name = [[.goproto.protoc.proto2.Layer1.Layer2]],
                    json_name = [[l2]],
                },
                {
                    name = [[l3]],
                    number = 2,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_MESSAGE]],
                    type_name = [[.goproto.protoc.proto2.Layer1.Layer2.Layer3]],
                    json_name = [[l3]],
                },
            },
            nested_type = {
                {
                    name = [[Layer2]],
                    field = {
                        {
                            name = [[l3]],
                            number = 1,
                            label = [[LABEL_OPTIONAL]],
                            type = [[TYPE_MESSAGE]],
                            type_name = [[.goproto.protoc.proto2.Layer1.Layer2.Layer3]],
                            json_name = [[l3]],
                        },
                    },
                    nested_type = {
                        {
                            name = [[Layer3]],
                        },
                    },
                },
            },
        },
    },
    options = {
        go_package = [[google.golang.org/protobuf/cmd/protoc-gen-go/testdata/proto2]],
    },
}