-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local proto2_proto2_pb_desc = require "proto2.proto2_pb_desc"

local proto2_proto2_pb = {}

---@class proto2_proto2_pb.Message
---@field i32 number
---@field m proto2_proto2_pb.Message

---@type fun():proto2_proto2_pb.Message @New a '.goproto.protoc.proto2.Message'
proto2_proto2_pb.Message = protobuf_reflect.Message(proto2_proto2_pb_desc.message_type[1])


return proto2_proto2_pb
