-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local proto2_proto2_pb_desc = require "proto2.proto2_pb_desc"

local proto2_proto2_pb = {}

---@class proto2_proto2_pb.Message : protobuf.Message
---@field i32 number
---@field m proto2_proto2_pb.Message

---@type fun():proto2_proto2_pb.Message
proto2_proto2_pb.Message = protobuf.Message(proto2_proto2_pb_desc.message_type[1])
proto2_proto2_pb.Message._FullName = ".goproto.protoc.proto2.Message"
proto2_proto2_pb.Message._Descriptor = "proto2_proto2_pb_desc.message_type[1]"
registry.RegistMessage(proto2_proto2_pb.Message)


return proto2_proto2_pb
