-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local imports_test_a_1_m1_pb_desc = require "imports.test_a_1.m1_pb_desc"

local imports_test_a_1_m1_pb = {}

---@alias imports_test_a_1_m1_pb.E1
---| 'imports_test_a_1_m1_pb.E1.E1_ZERO' # = 0

---@class imports_test_a_1_m1_pb.M1 : protobuf.Message

---@class imports_test_a_1_m1_pb.M1_1 : protobuf.Message
---@field m1 imports_test_a_1_m1_pb.M1

imports_test_a_1_m1_pb.E1 = {}
imports_test_a_1_m1_pb.E1._FullName = ".test.a.E1"
imports_test_a_1_m1_pb.E1._Descriptor = "imports_test_a_1_m1_pb_desc.enum_type[1]"
imports_test_a_1_m1_pb.E1.E1_ZERO = 0
imports_test_a_1_m1_pb.E1[0] = ".test.a.E1.E1_ZERO"
registry.RegistEnum(imports_test_a_1_m1_pb.E1)

---@type fun():imports_test_a_1_m1_pb.M1
imports_test_a_1_m1_pb.M1 = protobuf.Message(imports_test_a_1_m1_pb_desc.message_type[1])
imports_test_a_1_m1_pb.M1._FullName = ".test.a.M1"
imports_test_a_1_m1_pb.M1._Descriptor = "imports_test_a_1_m1_pb_desc.message_type[1]"
registry.RegistMessage(imports_test_a_1_m1_pb.M1)

---@type fun():imports_test_a_1_m1_pb.M1_1
imports_test_a_1_m1_pb.M1_1 = protobuf.Message(imports_test_a_1_m1_pb_desc.message_type[2])
imports_test_a_1_m1_pb.M1_1._FullName = ".test.a.M1_1"
imports_test_a_1_m1_pb.M1_1._Descriptor = "imports_test_a_1_m1_pb_desc.message_type[2]"
registry.RegistMessage(imports_test_a_1_m1_pb.M1_1)


return imports_test_a_1_m1_pb
