-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local imports_test_a_1_m1_pb_desc = require "imports.test_a_1.m1_pb_desc"

local imports_test_a_1_m1_pb = {}

---@alias imports_test_a_1_m1_pb.E1
---| 'imports_test_a_1_m1_pb.E1.E1_ZERO' # = 0

---@class imports_test_a_1_m1_pb.M1

---@class imports_test_a_1_m1_pb.M1_1
---@field m1 imports_test_a_1_m1_pb.M1

imports_test_a_1_m1_pb.E1 = protobuf_reflect.Enum(imports_test_a_1_m1_pb_desc.enum_type[1])
imports_test_a_1_m1_pb.E1.E1_ZERO = 0

---@type fun():imports_test_a_1_m1_pb.M1 @New a '.test.a.M1'
imports_test_a_1_m1_pb.M1 = protobuf_reflect.Message(imports_test_a_1_m1_pb_desc.message_type[1])

---@type fun():imports_test_a_1_m1_pb.M1_1 @New a '.test.a.M1_1'
imports_test_a_1_m1_pb.M1_1 = protobuf_reflect.Message(imports_test_a_1_m1_pb_desc.message_type[2])


return imports_test_a_1_m1_pb
