-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local imports_test_a_1_m2_pb_desc = require "imports.test_a_1.m2_pb_desc"

local imports_test_a_1_m2_pb = {}

---@class imports_test_a_1_m2_pb.M2

---@type fun():imports_test_a_1_m2_pb.M2 @New a '.test.a.M2'
imports_test_a_1_m2_pb.M2 = protobuf_reflect.Message(imports_test_a_1_m2_pb_desc.message_type[1])


return imports_test_a_1_m2_pb
