-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

return {
    name = [[imports/test_a_1/m2.proto]],
    package = [[test.a]],
    message_type = {
        {
            name = [[M2]],
        },
    },
    options = {
        go_package = [[google.golang.org/protobuf/cmd/protoc-gen-go/testdata/imports/test_a_1]],
    },
    syntax = [[proto3]],
}