-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local google_protobuf_any_pb_desc = require "google.protobuf.any_pb_desc"

local google_protobuf_any_pb = {}

---@class google_protobuf_any_pb.Any : protobuf.Message
---@field type_url string
---@field value string

---@type fun():google_protobuf_any_pb.Any
google_protobuf_any_pb.Any = protobuf.Message(google_protobuf_any_pb_desc.message_type[1])
google_protobuf_any_pb.Any._FullName = ".google.protobuf.Any"
google_protobuf_any_pb.Any._Descriptor = "google_protobuf_any_pb_desc.message_type[1]"
registry.RegistMessage(google_protobuf_any_pb.Any)


return google_protobuf_any_pb
