-- This file is generated by proto-gen-lua. DO NOT EDIT.
local google_protobuf_any_pb = {}

google_protobuf_any_pb.Any = {
    __call__ = function ()
        local message = {
            type_url = "",
            value = 0,
        }

        return message
    end,

}

return google_protobuf_any_pb
