-- This file is generated by proto-gen-lua. DO NOT EDIT.
local google_protobuf_source_context_pb = require "google.protobuf.source_context_pb"
local google_protobuf_type_pb = require "google.protobuf.type_pb"
local google_protobuf_api_pb = {}

google_protobuf_api_pb.Api = {
    __call__ = function ()
        local message = {
            name = "",
            methods = {},
            options = {},
            version = "",
            source_context = google_protobuf_source_context_pb.SourceContext(),
            mixins = {},
            syntax = 0,
        }

        return message
    end
,
}

google_protobuf_api_pb.Method = {
    __call__ = function ()
        local message = {
            name = "",
            request_type_url = "",
            request_streaming = 0,
            response_type_url = "",
            response_streaming = 0,
            options = {},
            syntax = 0,
        }

        return message
    end
,
}

google_protobuf_api_pb.Mixin = {
    __call__ = function ()
        local message = {
            name = "",
            root = "",
        }

        return message
    end
,
}

return google_protobuf_api_pb
