--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local source_context_pb = require("google.protobuf.source_context_pb")
local type_pb = require("google.protobuf.type_pb")
module('google.protobuf.api_pb')

API = protobuf.Descriptor();
API_NAME_FIELD = protobuf.FieldDescriptor();
API_METHODS_FIELD = protobuf.FieldDescriptor();
API_OPTIONS_FIELD = protobuf.FieldDescriptor();
API_VERSION_FIELD = protobuf.FieldDescriptor();
API_SOURCE_CONTEXT_FIELD = protobuf.FieldDescriptor();
API_MIXINS_FIELD = protobuf.FieldDescriptor();
API_SYNTAX_FIELD = protobuf.FieldDescriptor();
METHOD = protobuf.Descriptor();
METHOD_NAME_FIELD = protobuf.FieldDescriptor();
METHOD_REQUEST_TYPE_URL_FIELD = protobuf.FieldDescriptor();
METHOD_REQUEST_STREAMING_FIELD = protobuf.FieldDescriptor();
METHOD_RESPONSE_TYPE_URL_FIELD = protobuf.FieldDescriptor();
METHOD_RESPONSE_STREAMING_FIELD = protobuf.FieldDescriptor();
METHOD_OPTIONS_FIELD = protobuf.FieldDescriptor();
METHOD_SYNTAX_FIELD = protobuf.FieldDescriptor();
MIXIN = protobuf.Descriptor();
MIXIN_NAME_FIELD = protobuf.FieldDescriptor();
MIXIN_ROOT_FIELD = protobuf.FieldDescriptor();

API_NAME_FIELD.name = "name"
API_NAME_FIELD.full_name = ".google.protobuf.Api.name"
API_NAME_FIELD.number = 1
API_NAME_FIELD.index = 0
API_NAME_FIELD.label = 1
API_NAME_FIELD.has_default_value = false
API_NAME_FIELD.default_value = ""
API_NAME_FIELD.type = 9
API_NAME_FIELD.cpp_type = 9

API_METHODS_FIELD.name = "methods"
API_METHODS_FIELD.full_name = ".google.protobuf.Api.methods"
API_METHODS_FIELD.number = 2
API_METHODS_FIELD.index = 1
API_METHODS_FIELD.label = 3
API_METHODS_FIELD.has_default_value = false
API_METHODS_FIELD.default_value = {}
API_METHODS_FIELD.message_type = _METHOD
API_METHODS_FIELD.type = 11
API_METHODS_FIELD.cpp_type = 10

API_OPTIONS_FIELD.name = "options"
API_OPTIONS_FIELD.full_name = ".google.protobuf.Api.options"
API_OPTIONS_FIELD.number = 3
API_OPTIONS_FIELD.index = 2
API_OPTIONS_FIELD.label = 3
API_OPTIONS_FIELD.has_default_value = false
API_OPTIONS_FIELD.default_value = {}
API_OPTIONS_FIELD.message_type = google/protobuf/type_pb.OPTION
API_OPTIONS_FIELD.type = 11
API_OPTIONS_FIELD.cpp_type = 10

API_VERSION_FIELD.name = "version"
API_VERSION_FIELD.full_name = ".google.protobuf.Api.version"
API_VERSION_FIELD.number = 4
API_VERSION_FIELD.index = 3
API_VERSION_FIELD.label = 1
API_VERSION_FIELD.has_default_value = false
API_VERSION_FIELD.default_value = ""
API_VERSION_FIELD.type = 9
API_VERSION_FIELD.cpp_type = 9

API_SOURCE_CONTEXT_FIELD.name = "source_context"
API_SOURCE_CONTEXT_FIELD.full_name = ".google.protobuf.Api.source_context"
API_SOURCE_CONTEXT_FIELD.number = 5
API_SOURCE_CONTEXT_FIELD.index = 4
API_SOURCE_CONTEXT_FIELD.label = 1
API_SOURCE_CONTEXT_FIELD.has_default_value = false
API_SOURCE_CONTEXT_FIELD.default_value = nil
API_SOURCE_CONTEXT_FIELD.message_type = google/protobuf/source_context_pb.SOURCECONTEXT
API_SOURCE_CONTEXT_FIELD.type = 11
API_SOURCE_CONTEXT_FIELD.cpp_type = 10

API_MIXINS_FIELD.name = "mixins"
API_MIXINS_FIELD.full_name = ".google.protobuf.Api.mixins"
API_MIXINS_FIELD.number = 6
API_MIXINS_FIELD.index = 5
API_MIXINS_FIELD.label = 3
API_MIXINS_FIELD.has_default_value = false
API_MIXINS_FIELD.default_value = {}
API_MIXINS_FIELD.message_type = _MIXIN
API_MIXINS_FIELD.type = 11
API_MIXINS_FIELD.cpp_type = 10

API_SYNTAX_FIELD.name = "syntax"
API_SYNTAX_FIELD.full_name = ".google.protobuf.Api.syntax"
API_SYNTAX_FIELD.number = 7
API_SYNTAX_FIELD.index = 6
API_SYNTAX_FIELD.label = 1
API_SYNTAX_FIELD.has_default_value = false
API_SYNTAX_FIELD.default_value = nil
API_SYNTAX_FIELD.enum_type = google/protobuf/type_pb.SYNTAX
API_SYNTAX_FIELD.type = 14
API_SYNTAX_FIELD.cpp_type = 8

API.name = "Api"
API.full_name = ".google.protobuf.Api"
API.nested_types = {}
API.enum_types = {}
API.fields = {API_NAME_FIELD, API_METHODS_FIELD, API_OPTIONS_FIELD, API_VERSION_FIELD, API_SOURCE_CONTEXT_FIELD, API_MIXINS_FIELD, API_SYNTAX_FIELD}
API.is_extendable = false
API.extensions = {}
METHOD_NAME_FIELD.name = "name"
METHOD_NAME_FIELD.full_name = ".google.protobuf.Method.name"
METHOD_NAME_FIELD.number = 1
METHOD_NAME_FIELD.index = 0
METHOD_NAME_FIELD.label = 1
METHOD_NAME_FIELD.has_default_value = false
METHOD_NAME_FIELD.default_value = ""
METHOD_NAME_FIELD.type = 9
METHOD_NAME_FIELD.cpp_type = 9

METHOD_REQUEST_TYPE_URL_FIELD.name = "request_type_url"
METHOD_REQUEST_TYPE_URL_FIELD.full_name = ".google.protobuf.Method.request_type_url"
METHOD_REQUEST_TYPE_URL_FIELD.number = 2
METHOD_REQUEST_TYPE_URL_FIELD.index = 1
METHOD_REQUEST_TYPE_URL_FIELD.label = 1
METHOD_REQUEST_TYPE_URL_FIELD.has_default_value = false
METHOD_REQUEST_TYPE_URL_FIELD.default_value = ""
METHOD_REQUEST_TYPE_URL_FIELD.type = 9
METHOD_REQUEST_TYPE_URL_FIELD.cpp_type = 9

METHOD_REQUEST_STREAMING_FIELD.name = "request_streaming"
METHOD_REQUEST_STREAMING_FIELD.full_name = ".google.protobuf.Method.request_streaming"
METHOD_REQUEST_STREAMING_FIELD.number = 3
METHOD_REQUEST_STREAMING_FIELD.index = 2
METHOD_REQUEST_STREAMING_FIELD.label = 1
METHOD_REQUEST_STREAMING_FIELD.has_default_value = false
METHOD_REQUEST_STREAMING_FIELD.default_value = false
METHOD_REQUEST_STREAMING_FIELD.type = 8
METHOD_REQUEST_STREAMING_FIELD.cpp_type = 7

METHOD_RESPONSE_TYPE_URL_FIELD.name = "response_type_url"
METHOD_RESPONSE_TYPE_URL_FIELD.full_name = ".google.protobuf.Method.response_type_url"
METHOD_RESPONSE_TYPE_URL_FIELD.number = 4
METHOD_RESPONSE_TYPE_URL_FIELD.index = 3
METHOD_RESPONSE_TYPE_URL_FIELD.label = 1
METHOD_RESPONSE_TYPE_URL_FIELD.has_default_value = false
METHOD_RESPONSE_TYPE_URL_FIELD.default_value = ""
METHOD_RESPONSE_TYPE_URL_FIELD.type = 9
METHOD_RESPONSE_TYPE_URL_FIELD.cpp_type = 9

METHOD_RESPONSE_STREAMING_FIELD.name = "response_streaming"
METHOD_RESPONSE_STREAMING_FIELD.full_name = ".google.protobuf.Method.response_streaming"
METHOD_RESPONSE_STREAMING_FIELD.number = 5
METHOD_RESPONSE_STREAMING_FIELD.index = 4
METHOD_RESPONSE_STREAMING_FIELD.label = 1
METHOD_RESPONSE_STREAMING_FIELD.has_default_value = false
METHOD_RESPONSE_STREAMING_FIELD.default_value = false
METHOD_RESPONSE_STREAMING_FIELD.type = 8
METHOD_RESPONSE_STREAMING_FIELD.cpp_type = 7

METHOD_OPTIONS_FIELD.name = "options"
METHOD_OPTIONS_FIELD.full_name = ".google.protobuf.Method.options"
METHOD_OPTIONS_FIELD.number = 6
METHOD_OPTIONS_FIELD.index = 5
METHOD_OPTIONS_FIELD.label = 3
METHOD_OPTIONS_FIELD.has_default_value = false
METHOD_OPTIONS_FIELD.default_value = {}
METHOD_OPTIONS_FIELD.message_type = google/protobuf/type_pb.OPTION
METHOD_OPTIONS_FIELD.type = 11
METHOD_OPTIONS_FIELD.cpp_type = 10

METHOD_SYNTAX_FIELD.name = "syntax"
METHOD_SYNTAX_FIELD.full_name = ".google.protobuf.Method.syntax"
METHOD_SYNTAX_FIELD.number = 7
METHOD_SYNTAX_FIELD.index = 6
METHOD_SYNTAX_FIELD.label = 1
METHOD_SYNTAX_FIELD.has_default_value = false
METHOD_SYNTAX_FIELD.default_value = nil
METHOD_SYNTAX_FIELD.enum_type = google/protobuf/type_pb.SYNTAX
METHOD_SYNTAX_FIELD.type = 14
METHOD_SYNTAX_FIELD.cpp_type = 8

METHOD.name = "Method"
METHOD.full_name = ".google.protobuf.Method"
METHOD.nested_types = {}
METHOD.enum_types = {}
METHOD.fields = {METHOD_NAME_FIELD, METHOD_REQUEST_TYPE_URL_FIELD, METHOD_REQUEST_STREAMING_FIELD, METHOD_RESPONSE_TYPE_URL_FIELD, METHOD_RESPONSE_STREAMING_FIELD, METHOD_OPTIONS_FIELD, METHOD_SYNTAX_FIELD}
METHOD.is_extendable = false
METHOD.extensions = {}
MIXIN_NAME_FIELD.name = "name"
MIXIN_NAME_FIELD.full_name = ".google.protobuf.Mixin.name"
MIXIN_NAME_FIELD.number = 1
MIXIN_NAME_FIELD.index = 0
MIXIN_NAME_FIELD.label = 1
MIXIN_NAME_FIELD.has_default_value = false
MIXIN_NAME_FIELD.default_value = ""
MIXIN_NAME_FIELD.type = 9
MIXIN_NAME_FIELD.cpp_type = 9

MIXIN_ROOT_FIELD.name = "root"
MIXIN_ROOT_FIELD.full_name = ".google.protobuf.Mixin.root"
MIXIN_ROOT_FIELD.number = 2
MIXIN_ROOT_FIELD.index = 1
MIXIN_ROOT_FIELD.label = 1
MIXIN_ROOT_FIELD.has_default_value = false
MIXIN_ROOT_FIELD.default_value = ""
MIXIN_ROOT_FIELD.type = 9
MIXIN_ROOT_FIELD.cpp_type = 9

MIXIN.name = "Mixin"
MIXIN.full_name = ".google.protobuf.Mixin"
MIXIN.nested_types = {}
MIXIN.enum_types = {}
MIXIN.fields = {MIXIN_NAME_FIELD, MIXIN_ROOT_FIELD}
MIXIN.is_extendable = false
MIXIN.extensions = {}

Api = protobuf.Message(API)
Method = protobuf.Message(METHOD)
Mixin = protobuf.Message(MIXIN)

