-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local google_protobuf_descriptor_pb = {}

google_protobuf_descriptor_pb.FileDescriptorSet = setmetatable({}, {
    __call = function ()
        local default = {
            file = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.FileDescriptorSet)
    end
})

google_protobuf_descriptor_pb.FileDescriptorProto = setmetatable({}, {
    __call = function ()
        local default = {
            name = "",
            package = "",
            dependency = {},
            public_dependency = {},
            weak_dependency = {},
            message_type = {},
            enum_type = {},
            service = {},
            extension = {},
            options = {},
            source_code_info = {},
            syntax = "",
        }
        return setmetatable(default, google_protobuf_descriptor_pb.FileDescriptorProto)
    end
})

google_protobuf_descriptor_pb.DescriptorProto = setmetatable({}, {
    __call = function ()
        local default = {
            name = "",
            field = {},
            extension = {},
            nested_type = {},
            enum_type = {},
            extension_range = {},
            oneof_decl = {},
            options = {},
            reserved_range = {},
            reserved_name = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.DescriptorProto)
    end
})

google_protobuf_descriptor_pb.DescriptorProto.ExtensionRange = setmetatable({}, {
    __call = function ()
        local default = {
            start = 0,
            end_ = 0,
            options = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.DescriptorProto.ExtensionRange)
    end
})

google_protobuf_descriptor_pb.DescriptorProto.ReservedRange = setmetatable({}, {
    __call = function ()
        local default = {
            start = 0,
            end_ = 0,
        }
        return setmetatable(default, google_protobuf_descriptor_pb.DescriptorProto.ReservedRange)
    end
})

google_protobuf_descriptor_pb.ExtensionRangeOptions = setmetatable({}, {
    __call = function ()
        local default = {
            uninterpreted_option = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.ExtensionRangeOptions)
    end
})

google_protobuf_descriptor_pb.FieldDescriptorProto = setmetatable({}, {
    __call = function ()
        local default = {
            name = "",
            number = 0,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_DOUBLE,
            type_name = "",
            extendee = "",
            default_value = "",
            oneof_index = 0,
            json_name = "",
            options = {},
            proto3_optional = false,
        }
        return setmetatable(default, google_protobuf_descriptor_pb.FieldDescriptorProto)
    end
})

google_protobuf_descriptor_pb.FieldDescriptorProto.Type = {
    TYPE_DOUBLE = 1,
    TYPE_FLOAT = 2,
    TYPE_INT64 = 3,
    TYPE_UINT64 = 4,
    TYPE_INT32 = 5,
    TYPE_FIXED64 = 6,
    TYPE_FIXED32 = 7,
    TYPE_BOOL = 8,
    TYPE_STRING = 9,
    TYPE_GROUP = 10,
    TYPE_MESSAGE = 11,
    TYPE_BYTES = 12,
    TYPE_UINT32 = 13,
    TYPE_ENUM = 14,
    TYPE_SFIXED32 = 15,
    TYPE_SFIXED64 = 16,
    TYPE_SINT32 = 17,
    TYPE_SINT64 = 18,
}

google_protobuf_descriptor_pb.FieldDescriptorProto.Label = {
    LABEL_OPTIONAL = 1,
    LABEL_REQUIRED = 2,
    LABEL_REPEATED = 3,
}

google_protobuf_descriptor_pb.OneofDescriptorProto = setmetatable({}, {
    __call = function ()
        local default = {
            name = "",
            options = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.OneofDescriptorProto)
    end
})

google_protobuf_descriptor_pb.EnumDescriptorProto = setmetatable({}, {
    __call = function ()
        local default = {
            name = "",
            value = {},
            options = {},
            reserved_range = {},
            reserved_name = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.EnumDescriptorProto)
    end
})

google_protobuf_descriptor_pb.EnumDescriptorProto.EnumReservedRange = setmetatable({}, {
    __call = function ()
        local default = {
            start = 0,
            end_ = 0,
        }
        return setmetatable(default, google_protobuf_descriptor_pb.EnumDescriptorProto.EnumReservedRange)
    end
})

google_protobuf_descriptor_pb.EnumValueDescriptorProto = setmetatable({}, {
    __call = function ()
        local default = {
            name = "",
            number = 0,
            options = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.EnumValueDescriptorProto)
    end
})

google_protobuf_descriptor_pb.ServiceDescriptorProto = setmetatable({}, {
    __call = function ()
        local default = {
            name = "",
            method = {},
            options = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.ServiceDescriptorProto)
    end
})

google_protobuf_descriptor_pb.MethodDescriptorProto = setmetatable({}, {
    __call = function ()
        local default = {
            name = "",
            input_type = "",
            output_type = "",
            options = {},
            client_streaming = false,
            server_streaming = false,
        }
        return setmetatable(default, google_protobuf_descriptor_pb.MethodDescriptorProto)
    end
})

google_protobuf_descriptor_pb.FileOptions = setmetatable({}, {
    __call = function ()
        local default = {
            java_package = "",
            java_outer_classname = "",
            java_multiple_files = false,
            java_generate_equals_and_hash = false,
            java_string_check_utf8 = false,
            optimize_for = google_protobuf_descriptor_pb.FileOptions.OptimizeMode.SPEED,
            go_package = "",
            cc_generic_services = false,
            java_generic_services = false,
            py_generic_services = false,
            php_generic_services = false,
            deprecated = false,
            cc_enable_arenas = true,
            objc_class_prefix = "",
            csharp_namespace = "",
            swift_prefix = "",
            php_class_prefix = "",
            php_namespace = "",
            php_metadata_namespace = "",
            ruby_package = "",
            uninterpreted_option = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.FileOptions)
    end
})

google_protobuf_descriptor_pb.FileOptions.OptimizeMode = {
    SPEED = 1,
    CODE_SIZE = 2,
    LITE_RUNTIME = 3,
}

google_protobuf_descriptor_pb.MessageOptions = setmetatable({}, {
    __call = function ()
        local default = {
            message_set_wire_format = false,
            no_standard_descriptor_accessor = false,
            deprecated = false,
            map_entry = false,
            uninterpreted_option = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.MessageOptions)
    end
})

google_protobuf_descriptor_pb.FieldOptions = setmetatable({}, {
    __call = function ()
        local default = {
            ctype = google_protobuf_descriptor_pb.FieldOptions.CType.STRING,
            packed = false,
            jstype = google_protobuf_descriptor_pb.FieldOptions.JSType.JS_NORMAL,
            lazy = false,
            deprecated = false,
            weak = false,
            uninterpreted_option = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.FieldOptions)
    end
})

google_protobuf_descriptor_pb.FieldOptions.CType = {
    STRING = 0,
    CORD = 1,
    STRING_PIECE = 2,
}

google_protobuf_descriptor_pb.FieldOptions.JSType = {
    JS_NORMAL = 0,
    JS_STRING = 1,
    JS_NUMBER = 2,
}

google_protobuf_descriptor_pb.OneofOptions = setmetatable({}, {
    __call = function ()
        local default = {
            uninterpreted_option = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.OneofOptions)
    end
})

google_protobuf_descriptor_pb.EnumOptions = setmetatable({}, {
    __call = function ()
        local default = {
            allow_alias = false,
            deprecated = false,
            uninterpreted_option = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.EnumOptions)
    end
})

google_protobuf_descriptor_pb.EnumValueOptions = setmetatable({}, {
    __call = function ()
        local default = {
            deprecated = false,
            uninterpreted_option = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.EnumValueOptions)
    end
})

google_protobuf_descriptor_pb.ServiceOptions = setmetatable({}, {
    __call = function ()
        local default = {
            deprecated = false,
            uninterpreted_option = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.ServiceOptions)
    end
})

google_protobuf_descriptor_pb.MethodOptions = setmetatable({}, {
    __call = function ()
        local default = {
            deprecated = false,
            idempotency_level = google_protobuf_descriptor_pb.MethodOptions.IdempotencyLevel.IDEMPOTENCY_UNKNOWN,
            uninterpreted_option = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.MethodOptions)
    end
})

google_protobuf_descriptor_pb.MethodOptions.IdempotencyLevel = {
    IDEMPOTENCY_UNKNOWN = 0,
    NO_SIDE_EFFECTS = 1,
    IDEMPOTENT = 2,
}

google_protobuf_descriptor_pb.UninterpretedOption = setmetatable({}, {
    __call = function ()
        local default = {
            name = {},
            identifier_value = "",
            positive_int_value = 0,
            negative_int_value = 0,
            double_value = 0.0,
            string_value = "",
            aggregate_value = "",
        }
        return setmetatable(default, google_protobuf_descriptor_pb.UninterpretedOption)
    end
})

google_protobuf_descriptor_pb.UninterpretedOption.NamePart = setmetatable({}, {
    __call = function ()
        local default = {
            name_part = "",
            is_extension = false,
        }
        return setmetatable(default, google_protobuf_descriptor_pb.UninterpretedOption.NamePart)
    end
})

google_protobuf_descriptor_pb.SourceCodeInfo = setmetatable({}, {
    __call = function ()
        local default = {
            location = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.SourceCodeInfo)
    end
})

google_protobuf_descriptor_pb.SourceCodeInfo.Location = setmetatable({}, {
    __call = function ()
        local default = {
            path = {},
            span = {},
            leading_comments = "",
            trailing_comments = "",
            leading_detached_comments = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.SourceCodeInfo.Location)
    end
})

google_protobuf_descriptor_pb.GeneratedCodeInfo = setmetatable({}, {
    __call = function ()
        local default = {
            annotation = {},
        }
        return setmetatable(default, google_protobuf_descriptor_pb.GeneratedCodeInfo)
    end
})

google_protobuf_descriptor_pb.GeneratedCodeInfo.Annotation = setmetatable({}, {
    __call = function ()
        local default = {
            path = {},
            source_file = "",
            begin = 0,
            end_ = 0,
        }
        return setmetatable(default, google_protobuf_descriptor_pb.GeneratedCodeInfo.Annotation)
    end
})

----------------- Descriptor -----------------

google_protobuf_descriptor_pb.FileDescriptorSet.Descriptor = {
    name = ".google.protobuf.FileDescriptorSet",
    field = {
        file = {
            name = ".google.protobuf.FileDescriptorSet.file",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.FileDescriptorProto",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.FileDescriptorProto.Descriptor = {
    name = ".google.protobuf.FileDescriptorProto",
    field = {
        name = {
            name = ".google.protobuf.FileDescriptorProto.name",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        package = {
            name = ".google.protobuf.FileDescriptorProto.package",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        dependency = {
            name = ".google.protobuf.FileDescriptorProto.dependency",
            number = 3,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        public_dependency = {
            name = ".google.protobuf.FileDescriptorProto.public_dependency",
            number = 10,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT32,
            options = {
                packed = false,
            }
        },
        weak_dependency = {
            name = ".google.protobuf.FileDescriptorProto.weak_dependency",
            number = 11,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT32,
            options = {
                packed = false,
            }
        },
        message_type = {
            name = ".google.protobuf.FileDescriptorProto.message_type",
            number = 4,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.DescriptorProto",
            options = {
                packed = false,
            }
        },
        enum_type = {
            name = ".google.protobuf.FileDescriptorProto.enum_type",
            number = 5,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.EnumDescriptorProto",
            options = {
                packed = false,
            }
        },
        service = {
            name = ".google.protobuf.FileDescriptorProto.service",
            number = 6,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.ServiceDescriptorProto",
            options = {
                packed = false,
            }
        },
        extension = {
            name = ".google.protobuf.FileDescriptorProto.extension",
            number = 7,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.FieldDescriptorProto",
            options = {
                packed = false,
            }
        },
        options = {
            name = ".google.protobuf.FileDescriptorProto.options",
            number = 8,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.FileOptions",
            options = {
                packed = false,
            }
        },
        source_code_info = {
            name = ".google.protobuf.FileDescriptorProto.source_code_info",
            number = 9,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.SourceCodeInfo",
            options = {
                packed = false,
            }
        },
        syntax = {
            name = ".google.protobuf.FileDescriptorProto.syntax",
            number = 12,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.DescriptorProto.ExtensionRange.Descriptor = {
    name = ".google.protobuf.DescriptorProto.ExtensionRange",
    field = {
        start = {
            name = ".google.protobuf.DescriptorProto.ExtensionRange.start",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT32,
            options = {
                packed = false,
            }
        },
        end_ = {
            name = ".google.protobuf.DescriptorProto.ExtensionRange.end",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT32,
            options = {
                packed = false,
            }
        },
        options = {
            name = ".google.protobuf.DescriptorProto.ExtensionRange.options",
            number = 3,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.ExtensionRangeOptions",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.DescriptorProto.ReservedRange.Descriptor = {
    name = ".google.protobuf.DescriptorProto.ReservedRange",
    field = {
        start = {
            name = ".google.protobuf.DescriptorProto.ReservedRange.start",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT32,
            options = {
                packed = false,
            }
        },
        end_ = {
            name = ".google.protobuf.DescriptorProto.ReservedRange.end",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT32,
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.DescriptorProto.Descriptor = {
    name = ".google.protobuf.DescriptorProto",
    field = {
        name = {
            name = ".google.protobuf.DescriptorProto.name",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        field = {
            name = ".google.protobuf.DescriptorProto.field",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.FieldDescriptorProto",
            options = {
                packed = false,
            }
        },
        extension = {
            name = ".google.protobuf.DescriptorProto.extension",
            number = 6,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.FieldDescriptorProto",
            options = {
                packed = false,
            }
        },
        nested_type = {
            name = ".google.protobuf.DescriptorProto.nested_type",
            number = 3,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.DescriptorProto",
            options = {
                packed = false,
            }
        },
        enum_type = {
            name = ".google.protobuf.DescriptorProto.enum_type",
            number = 4,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.EnumDescriptorProto",
            options = {
                packed = false,
            }
        },
        extension_range = {
            name = ".google.protobuf.DescriptorProto.extension_range",
            number = 5,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.DescriptorProto.ExtensionRange",
            options = {
                packed = false,
            }
        },
        oneof_decl = {
            name = ".google.protobuf.DescriptorProto.oneof_decl",
            number = 8,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.OneofDescriptorProto",
            options = {
                packed = false,
            }
        },
        options = {
            name = ".google.protobuf.DescriptorProto.options",
            number = 7,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.MessageOptions",
            options = {
                packed = false,
            }
        },
        reserved_range = {
            name = ".google.protobuf.DescriptorProto.reserved_range",
            number = 9,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.DescriptorProto.ReservedRange",
            options = {
                packed = false,
            }
        },
        reserved_name = {
            name = ".google.protobuf.DescriptorProto.reserved_name",
            number = 10,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.ExtensionRangeOptions.Descriptor = {
    name = ".google.protobuf.ExtensionRangeOptions",
    field = {
        uninterpreted_option = {
            name = ".google.protobuf.ExtensionRangeOptions.uninterpreted_option",
            number = 999,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.UninterpretedOption",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.Descriptor = {
    name = ".google.protobuf.FieldDescriptorProto.Type",
}
google_protobuf_descriptor_pb.FieldDescriptorProto.Label.Descriptor = {
    name = ".google.protobuf.FieldDescriptorProto.Label",
}
google_protobuf_descriptor_pb.FieldDescriptorProto.Descriptor = {
    name = ".google.protobuf.FieldDescriptorProto",
    field = {
        name = {
            name = ".google.protobuf.FieldDescriptorProto.name",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        number = {
            name = ".google.protobuf.FieldDescriptorProto.number",
            number = 3,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT32,
            options = {
                packed = false,
            }
        },
        label = {
            name = ".google.protobuf.FieldDescriptorProto.label",
            number = 4,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_ENUM,
            type_name = ".google.protobuf.FieldDescriptorProto.Label",
            options = {
                packed = false,
            }
        },
        type = {
            name = ".google.protobuf.FieldDescriptorProto.type",
            number = 5,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_ENUM,
            type_name = ".google.protobuf.FieldDescriptorProto.Type",
            options = {
                packed = false,
            }
        },
        type_name = {
            name = ".google.protobuf.FieldDescriptorProto.type_name",
            number = 6,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        extendee = {
            name = ".google.protobuf.FieldDescriptorProto.extendee",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        default_value = {
            name = ".google.protobuf.FieldDescriptorProto.default_value",
            number = 7,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        oneof_index = {
            name = ".google.protobuf.FieldDescriptorProto.oneof_index",
            number = 9,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT32,
            options = {
                packed = false,
            }
        },
        json_name = {
            name = ".google.protobuf.FieldDescriptorProto.json_name",
            number = 10,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        options = {
            name = ".google.protobuf.FieldDescriptorProto.options",
            number = 8,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.FieldOptions",
            options = {
                packed = false,
            }
        },
        proto3_optional = {
            name = ".google.protobuf.FieldDescriptorProto.proto3_optional",
            number = 17,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.OneofDescriptorProto.Descriptor = {
    name = ".google.protobuf.OneofDescriptorProto",
    field = {
        name = {
            name = ".google.protobuf.OneofDescriptorProto.name",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        options = {
            name = ".google.protobuf.OneofDescriptorProto.options",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.OneofOptions",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.EnumDescriptorProto.EnumReservedRange.Descriptor = {
    name = ".google.protobuf.EnumDescriptorProto.EnumReservedRange",
    field = {
        start = {
            name = ".google.protobuf.EnumDescriptorProto.EnumReservedRange.start",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT32,
            options = {
                packed = false,
            }
        },
        end_ = {
            name = ".google.protobuf.EnumDescriptorProto.EnumReservedRange.end",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT32,
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.EnumDescriptorProto.Descriptor = {
    name = ".google.protobuf.EnumDescriptorProto",
    field = {
        name = {
            name = ".google.protobuf.EnumDescriptorProto.name",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        value = {
            name = ".google.protobuf.EnumDescriptorProto.value",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.EnumValueDescriptorProto",
            options = {
                packed = false,
            }
        },
        options = {
            name = ".google.protobuf.EnumDescriptorProto.options",
            number = 3,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.EnumOptions",
            options = {
                packed = false,
            }
        },
        reserved_range = {
            name = ".google.protobuf.EnumDescriptorProto.reserved_range",
            number = 4,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.EnumDescriptorProto.EnumReservedRange",
            options = {
                packed = false,
            }
        },
        reserved_name = {
            name = ".google.protobuf.EnumDescriptorProto.reserved_name",
            number = 5,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.EnumValueDescriptorProto.Descriptor = {
    name = ".google.protobuf.EnumValueDescriptorProto",
    field = {
        name = {
            name = ".google.protobuf.EnumValueDescriptorProto.name",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        number = {
            name = ".google.protobuf.EnumValueDescriptorProto.number",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT32,
            options = {
                packed = false,
            }
        },
        options = {
            name = ".google.protobuf.EnumValueDescriptorProto.options",
            number = 3,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.EnumValueOptions",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.ServiceDescriptorProto.Descriptor = {
    name = ".google.protobuf.ServiceDescriptorProto",
    field = {
        name = {
            name = ".google.protobuf.ServiceDescriptorProto.name",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        method = {
            name = ".google.protobuf.ServiceDescriptorProto.method",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.MethodDescriptorProto",
            options = {
                packed = false,
            }
        },
        options = {
            name = ".google.protobuf.ServiceDescriptorProto.options",
            number = 3,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.ServiceOptions",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.MethodDescriptorProto.Descriptor = {
    name = ".google.protobuf.MethodDescriptorProto",
    field = {
        name = {
            name = ".google.protobuf.MethodDescriptorProto.name",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        input_type = {
            name = ".google.protobuf.MethodDescriptorProto.input_type",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        output_type = {
            name = ".google.protobuf.MethodDescriptorProto.output_type",
            number = 3,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        options = {
            name = ".google.protobuf.MethodDescriptorProto.options",
            number = 4,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.MethodOptions",
            options = {
                packed = false,
            }
        },
        client_streaming = {
            name = ".google.protobuf.MethodDescriptorProto.client_streaming",
            number = 5,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        server_streaming = {
            name = ".google.protobuf.MethodDescriptorProto.server_streaming",
            number = 6,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.FileOptions.OptimizeMode.Descriptor = {
    name = ".google.protobuf.FileOptions.OptimizeMode",
}
google_protobuf_descriptor_pb.FileOptions.Descriptor = {
    name = ".google.protobuf.FileOptions",
    field = {
        java_package = {
            name = ".google.protobuf.FileOptions.java_package",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        java_outer_classname = {
            name = ".google.protobuf.FileOptions.java_outer_classname",
            number = 8,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        java_multiple_files = {
            name = ".google.protobuf.FileOptions.java_multiple_files",
            number = 10,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        java_generate_equals_and_hash = {
            name = ".google.protobuf.FileOptions.java_generate_equals_and_hash",
            number = 20,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        java_string_check_utf8 = {
            name = ".google.protobuf.FileOptions.java_string_check_utf8",
            number = 27,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        optimize_for = {
            name = ".google.protobuf.FileOptions.optimize_for",
            number = 9,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_ENUM,
            type_name = ".google.protobuf.FileOptions.OptimizeMode",
            options = {
                packed = false,
            }
        },
        go_package = {
            name = ".google.protobuf.FileOptions.go_package",
            number = 11,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        cc_generic_services = {
            name = ".google.protobuf.FileOptions.cc_generic_services",
            number = 16,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        java_generic_services = {
            name = ".google.protobuf.FileOptions.java_generic_services",
            number = 17,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        py_generic_services = {
            name = ".google.protobuf.FileOptions.py_generic_services",
            number = 18,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        php_generic_services = {
            name = ".google.protobuf.FileOptions.php_generic_services",
            number = 42,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        deprecated = {
            name = ".google.protobuf.FileOptions.deprecated",
            number = 23,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        cc_enable_arenas = {
            name = ".google.protobuf.FileOptions.cc_enable_arenas",
            number = 31,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        objc_class_prefix = {
            name = ".google.protobuf.FileOptions.objc_class_prefix",
            number = 36,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        csharp_namespace = {
            name = ".google.protobuf.FileOptions.csharp_namespace",
            number = 37,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        swift_prefix = {
            name = ".google.protobuf.FileOptions.swift_prefix",
            number = 39,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        php_class_prefix = {
            name = ".google.protobuf.FileOptions.php_class_prefix",
            number = 40,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        php_namespace = {
            name = ".google.protobuf.FileOptions.php_namespace",
            number = 41,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        php_metadata_namespace = {
            name = ".google.protobuf.FileOptions.php_metadata_namespace",
            number = 44,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        ruby_package = {
            name = ".google.protobuf.FileOptions.ruby_package",
            number = 45,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        uninterpreted_option = {
            name = ".google.protobuf.FileOptions.uninterpreted_option",
            number = 999,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.UninterpretedOption",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.MessageOptions.Descriptor = {
    name = ".google.protobuf.MessageOptions",
    field = {
        message_set_wire_format = {
            name = ".google.protobuf.MessageOptions.message_set_wire_format",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        no_standard_descriptor_accessor = {
            name = ".google.protobuf.MessageOptions.no_standard_descriptor_accessor",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        deprecated = {
            name = ".google.protobuf.MessageOptions.deprecated",
            number = 3,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        map_entry = {
            name = ".google.protobuf.MessageOptions.map_entry",
            number = 7,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        uninterpreted_option = {
            name = ".google.protobuf.MessageOptions.uninterpreted_option",
            number = 999,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.UninterpretedOption",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.FieldOptions.CType.Descriptor = {
    name = ".google.protobuf.FieldOptions.CType",
}
google_protobuf_descriptor_pb.FieldOptions.JSType.Descriptor = {
    name = ".google.protobuf.FieldOptions.JSType",
}
google_protobuf_descriptor_pb.FieldOptions.Descriptor = {
    name = ".google.protobuf.FieldOptions",
    field = {
        ctype = {
            name = ".google.protobuf.FieldOptions.ctype",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_ENUM,
            type_name = ".google.protobuf.FieldOptions.CType",
            options = {
                packed = false,
            }
        },
        packed = {
            name = ".google.protobuf.FieldOptions.packed",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        jstype = {
            name = ".google.protobuf.FieldOptions.jstype",
            number = 6,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_ENUM,
            type_name = ".google.protobuf.FieldOptions.JSType",
            options = {
                packed = false,
            }
        },
        lazy = {
            name = ".google.protobuf.FieldOptions.lazy",
            number = 5,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        deprecated = {
            name = ".google.protobuf.FieldOptions.deprecated",
            number = 3,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        weak = {
            name = ".google.protobuf.FieldOptions.weak",
            number = 10,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        uninterpreted_option = {
            name = ".google.protobuf.FieldOptions.uninterpreted_option",
            number = 999,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.UninterpretedOption",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.OneofOptions.Descriptor = {
    name = ".google.protobuf.OneofOptions",
    field = {
        uninterpreted_option = {
            name = ".google.protobuf.OneofOptions.uninterpreted_option",
            number = 999,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.UninterpretedOption",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.EnumOptions.Descriptor = {
    name = ".google.protobuf.EnumOptions",
    field = {
        allow_alias = {
            name = ".google.protobuf.EnumOptions.allow_alias",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        deprecated = {
            name = ".google.protobuf.EnumOptions.deprecated",
            number = 3,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        uninterpreted_option = {
            name = ".google.protobuf.EnumOptions.uninterpreted_option",
            number = 999,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.UninterpretedOption",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.EnumValueOptions.Descriptor = {
    name = ".google.protobuf.EnumValueOptions",
    field = {
        deprecated = {
            name = ".google.protobuf.EnumValueOptions.deprecated",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        uninterpreted_option = {
            name = ".google.protobuf.EnumValueOptions.uninterpreted_option",
            number = 999,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.UninterpretedOption",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.ServiceOptions.Descriptor = {
    name = ".google.protobuf.ServiceOptions",
    field = {
        deprecated = {
            name = ".google.protobuf.ServiceOptions.deprecated",
            number = 33,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        uninterpreted_option = {
            name = ".google.protobuf.ServiceOptions.uninterpreted_option",
            number = 999,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.UninterpretedOption",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.MethodOptions.IdempotencyLevel.Descriptor = {
    name = ".google.protobuf.MethodOptions.IdempotencyLevel",
}
google_protobuf_descriptor_pb.MethodOptions.Descriptor = {
    name = ".google.protobuf.MethodOptions",
    field = {
        deprecated = {
            name = ".google.protobuf.MethodOptions.deprecated",
            number = 33,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        idempotency_level = {
            name = ".google.protobuf.MethodOptions.idempotency_level",
            number = 34,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_ENUM,
            type_name = ".google.protobuf.MethodOptions.IdempotencyLevel",
            options = {
                packed = false,
            }
        },
        uninterpreted_option = {
            name = ".google.protobuf.MethodOptions.uninterpreted_option",
            number = 999,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.UninterpretedOption",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.UninterpretedOption.NamePart.Descriptor = {
    name = ".google.protobuf.UninterpretedOption.NamePart",
    field = {
        name_part = {
            name = ".google.protobuf.UninterpretedOption.NamePart.name_part",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REQUIRED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        is_extension = {
            name = ".google.protobuf.UninterpretedOption.NamePart.is_extension",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REQUIRED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.UninterpretedOption.Descriptor = {
    name = ".google.protobuf.UninterpretedOption",
    field = {
        name = {
            name = ".google.protobuf.UninterpretedOption.name",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.UninterpretedOption.NamePart",
            options = {
                packed = false,
            }
        },
        identifier_value = {
            name = ".google.protobuf.UninterpretedOption.identifier_value",
            number = 3,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        positive_int_value = {
            name = ".google.protobuf.UninterpretedOption.positive_int_value",
            number = 4,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_UINT64,
            options = {
                packed = false,
            }
        },
        negative_int_value = {
            name = ".google.protobuf.UninterpretedOption.negative_int_value",
            number = 5,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT64,
            options = {
                packed = false,
            }
        },
        double_value = {
            name = ".google.protobuf.UninterpretedOption.double_value",
            number = 6,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_DOUBLE,
            options = {
                packed = false,
            }
        },
        string_value = {
            name = ".google.protobuf.UninterpretedOption.string_value",
            number = 7,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BYTES,
            options = {
                packed = false,
            }
        },
        aggregate_value = {
            name = ".google.protobuf.UninterpretedOption.aggregate_value",
            number = 8,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.SourceCodeInfo.Location.Descriptor = {
    name = ".google.protobuf.SourceCodeInfo.Location",
    field = {
        path = {
            name = ".google.protobuf.SourceCodeInfo.Location.path",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT32,
            options = {
                packed = true,
            }
        },
        span = {
            name = ".google.protobuf.SourceCodeInfo.Location.span",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT32,
            options = {
                packed = true,
            }
        },
        leading_comments = {
            name = ".google.protobuf.SourceCodeInfo.Location.leading_comments",
            number = 3,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        trailing_comments = {
            name = ".google.protobuf.SourceCodeInfo.Location.trailing_comments",
            number = 4,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        leading_detached_comments = {
            name = ".google.protobuf.SourceCodeInfo.Location.leading_detached_comments",
            number = 6,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.SourceCodeInfo.Descriptor = {
    name = ".google.protobuf.SourceCodeInfo",
    field = {
        location = {
            name = ".google.protobuf.SourceCodeInfo.location",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.SourceCodeInfo.Location",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.GeneratedCodeInfo.Annotation.Descriptor = {
    name = ".google.protobuf.GeneratedCodeInfo.Annotation",
    field = {
        path = {
            name = ".google.protobuf.GeneratedCodeInfo.Annotation.path",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT32,
            options = {
                packed = true,
            }
        },
        source_file = {
            name = ".google.protobuf.GeneratedCodeInfo.Annotation.source_file",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        begin = {
            name = ".google.protobuf.GeneratedCodeInfo.Annotation.begin",
            number = 3,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT32,
            options = {
                packed = false,
            }
        },
        end_ = {
            name = ".google.protobuf.GeneratedCodeInfo.Annotation.end",
            number = 4,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT32,
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.GeneratedCodeInfo.Descriptor = {
    name = ".google.protobuf.GeneratedCodeInfo",
    field = {
        annotation = {
            name = ".google.protobuf.GeneratedCodeInfo.annotation",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.GeneratedCodeInfo.Annotation",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_descriptor_pb.Descriptor = {
    name = "google/protobuf/descriptor.proto",
    package = "google.protobuf",
    message_type = {
        google_protobuf_descriptor_pb.FileDescriptorSet.Descriptor,
        google_protobuf_descriptor_pb.FileDescriptorProto.Descriptor,
        google_protobuf_descriptor_pb.DescriptorProto.Descriptor,
        google_protobuf_descriptor_pb.ExtensionRangeOptions.Descriptor,
        google_protobuf_descriptor_pb.FieldDescriptorProto.Descriptor,
        google_protobuf_descriptor_pb.OneofDescriptorProto.Descriptor,
        google_protobuf_descriptor_pb.EnumDescriptorProto.Descriptor,
        google_protobuf_descriptor_pb.EnumValueDescriptorProto.Descriptor,
        google_protobuf_descriptor_pb.ServiceDescriptorProto.Descriptor,
        google_protobuf_descriptor_pb.MethodDescriptorProto.Descriptor,
        google_protobuf_descriptor_pb.FileOptions.Descriptor,
        google_protobuf_descriptor_pb.MessageOptions.Descriptor,
        google_protobuf_descriptor_pb.FieldOptions.Descriptor,
        google_protobuf_descriptor_pb.OneofOptions.Descriptor,
        google_protobuf_descriptor_pb.EnumOptions.Descriptor,
        google_protobuf_descriptor_pb.EnumValueOptions.Descriptor,
        google_protobuf_descriptor_pb.ServiceOptions.Descriptor,
        google_protobuf_descriptor_pb.MethodOptions.Descriptor,
        google_protobuf_descriptor_pb.UninterpretedOption.Descriptor,
        google_protobuf_descriptor_pb.SourceCodeInfo.Descriptor,
        google_protobuf_descriptor_pb.GeneratedCodeInfo.Descriptor,
    },
}
return google_protobuf_descriptor_pb
