-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local google_protobuf_descriptor_pb_desc = require "google.protobuf.descriptor_pb_desc"

local google_protobuf_descriptor_pb = {}

---@class google_protobuf_descriptor_pb.FileDescriptorSet
---@field file google_protobuf_descriptor_pb.FileDescriptorProto[]

---@class google_protobuf_descriptor_pb.FileDescriptorProto
---@field name string
---@field package string
---@field dependency string[]
---@field public_dependency number[]
---@field weak_dependency number[]
---@field message_type google_protobuf_descriptor_pb.DescriptorProto[]
---@field enum_type google_protobuf_descriptor_pb.EnumDescriptorProto[]
---@field service google_protobuf_descriptor_pb.ServiceDescriptorProto[]
---@field extension google_protobuf_descriptor_pb.FieldDescriptorProto[]
---@field options google_protobuf_descriptor_pb.FileOptions
---@field source_code_info google_protobuf_descriptor_pb.SourceCodeInfo
---@field syntax string

---@class google_protobuf_descriptor_pb.DescriptorProto.ExtensionRange
---@field start number
---@field end number
---@field options google_protobuf_descriptor_pb.ExtensionRangeOptions

---@class google_protobuf_descriptor_pb.DescriptorProto.ReservedRange
---@field start number
---@field end number

---@class google_protobuf_descriptor_pb.DescriptorProto
---@field name string
---@field field google_protobuf_descriptor_pb.FieldDescriptorProto[]
---@field extension google_protobuf_descriptor_pb.FieldDescriptorProto[]
---@field nested_type google_protobuf_descriptor_pb.DescriptorProto[]
---@field enum_type google_protobuf_descriptor_pb.EnumDescriptorProto[]
---@field extension_range google_protobuf_descriptor_pb.DescriptorProto.ExtensionRange[]
---@field oneof_decl google_protobuf_descriptor_pb.OneofDescriptorProto[]
---@field options google_protobuf_descriptor_pb.MessageOptions
---@field reserved_range google_protobuf_descriptor_pb.DescriptorProto.ReservedRange[]
---@field reserved_name string[]

---@class google_protobuf_descriptor_pb.ExtensionRangeOptions
---@field uninterpreted_option google_protobuf_descriptor_pb.UninterpretedOption[]

---@alias google_protobuf_descriptor_pb.FieldDescriptorProto.Type
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_DOUBLE' # = 1
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_FLOAT' # = 2
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT64' # = 3
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_UINT64' # = 4
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT32' # = 5
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_FIXED64' # = 6
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_FIXED32' # = 7
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL' # = 8
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING' # = 9
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_GROUP' # = 10
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE' # = 11
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BYTES' # = 12
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_UINT32' # = 13
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_ENUM' # = 14
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_SFIXED32' # = 15
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_SFIXED64' # = 16
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_SINT32' # = 17
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_SINT64' # = 18

---@alias google_protobuf_descriptor_pb.FieldDescriptorProto.Label
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL' # = 1
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REQUIRED' # = 2
---| 'google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED' # = 3

---@class google_protobuf_descriptor_pb.FieldDescriptorProto
---@field name string
---@field number number
---@field label google_protobuf_descriptor_pb.FieldDescriptorProto.Label
---@field type google_protobuf_descriptor_pb.FieldDescriptorProto.Type
---@field type_name string
---@field extendee string
---@field default_value string
---@field oneof_index number
---@field json_name string
---@field options google_protobuf_descriptor_pb.FieldOptions
---@field proto3_optional boolean

---@class google_protobuf_descriptor_pb.OneofDescriptorProto
---@field name string
---@field options google_protobuf_descriptor_pb.OneofOptions

---@class google_protobuf_descriptor_pb.EnumDescriptorProto.EnumReservedRange
---@field start number
---@field end number

---@class google_protobuf_descriptor_pb.EnumDescriptorProto
---@field name string
---@field value google_protobuf_descriptor_pb.EnumValueDescriptorProto[]
---@field options google_protobuf_descriptor_pb.EnumOptions
---@field reserved_range google_protobuf_descriptor_pb.EnumDescriptorProto.EnumReservedRange[]
---@field reserved_name string[]

---@class google_protobuf_descriptor_pb.EnumValueDescriptorProto
---@field name string
---@field number number
---@field options google_protobuf_descriptor_pb.EnumValueOptions

---@class google_protobuf_descriptor_pb.ServiceDescriptorProto
---@field name string
---@field method google_protobuf_descriptor_pb.MethodDescriptorProto[]
---@field options google_protobuf_descriptor_pb.ServiceOptions

---@class google_protobuf_descriptor_pb.MethodDescriptorProto
---@field name string
---@field input_type string
---@field output_type string
---@field options google_protobuf_descriptor_pb.MethodOptions
---@field client_streaming boolean
---@field server_streaming boolean

---@alias google_protobuf_descriptor_pb.FileOptions.OptimizeMode
---| 'google_protobuf_descriptor_pb.FileOptions.OptimizeMode.SPEED' # = 1
---| 'google_protobuf_descriptor_pb.FileOptions.OptimizeMode.CODE_SIZE' # = 2
---| 'google_protobuf_descriptor_pb.FileOptions.OptimizeMode.LITE_RUNTIME' # = 3

---@class google_protobuf_descriptor_pb.FileOptions
---@field java_package string
---@field java_outer_classname string
---@field java_multiple_files boolean
---@field java_generate_equals_and_hash boolean
---@field java_string_check_utf8 boolean
---@field optimize_for google_protobuf_descriptor_pb.FileOptions.OptimizeMode
---@field go_package string
---@field cc_generic_services boolean
---@field java_generic_services boolean
---@field py_generic_services boolean
---@field php_generic_services boolean
---@field deprecated boolean
---@field cc_enable_arenas boolean
---@field objc_class_prefix string
---@field csharp_namespace string
---@field swift_prefix string
---@field php_class_prefix string
---@field php_namespace string
---@field php_metadata_namespace string
---@field ruby_package string
---@field uninterpreted_option google_protobuf_descriptor_pb.UninterpretedOption[]

---@class google_protobuf_descriptor_pb.MessageOptions
---@field message_set_wire_format boolean
---@field no_standard_descriptor_accessor boolean
---@field deprecated boolean
---@field map_entry boolean
---@field uninterpreted_option google_protobuf_descriptor_pb.UninterpretedOption[]

---@alias google_protobuf_descriptor_pb.FieldOptions.CType
---| 'google_protobuf_descriptor_pb.FieldOptions.CType.STRING' # = 0
---| 'google_protobuf_descriptor_pb.FieldOptions.CType.CORD' # = 1
---| 'google_protobuf_descriptor_pb.FieldOptions.CType.STRING_PIECE' # = 2

---@alias google_protobuf_descriptor_pb.FieldOptions.JSType
---| 'google_protobuf_descriptor_pb.FieldOptions.JSType.JS_NORMAL' # = 0
---| 'google_protobuf_descriptor_pb.FieldOptions.JSType.JS_STRING' # = 1
---| 'google_protobuf_descriptor_pb.FieldOptions.JSType.JS_NUMBER' # = 2

---@class google_protobuf_descriptor_pb.FieldOptions
---@field ctype google_protobuf_descriptor_pb.FieldOptions.CType
---@field packed boolean
---@field jstype google_protobuf_descriptor_pb.FieldOptions.JSType
---@field lazy boolean
---@field deprecated boolean
---@field weak boolean
---@field uninterpreted_option google_protobuf_descriptor_pb.UninterpretedOption[]

---@class google_protobuf_descriptor_pb.OneofOptions
---@field uninterpreted_option google_protobuf_descriptor_pb.UninterpretedOption[]

---@class google_protobuf_descriptor_pb.EnumOptions
---@field allow_alias boolean
---@field deprecated boolean
---@field uninterpreted_option google_protobuf_descriptor_pb.UninterpretedOption[]

---@class google_protobuf_descriptor_pb.EnumValueOptions
---@field deprecated boolean
---@field uninterpreted_option google_protobuf_descriptor_pb.UninterpretedOption[]

---@class google_protobuf_descriptor_pb.ServiceOptions
---@field deprecated boolean
---@field uninterpreted_option google_protobuf_descriptor_pb.UninterpretedOption[]

---@alias google_protobuf_descriptor_pb.MethodOptions.IdempotencyLevel
---| 'google_protobuf_descriptor_pb.MethodOptions.IdempotencyLevel.IDEMPOTENCY_UNKNOWN' # = 0
---| 'google_protobuf_descriptor_pb.MethodOptions.IdempotencyLevel.NO_SIDE_EFFECTS' # = 1
---| 'google_protobuf_descriptor_pb.MethodOptions.IdempotencyLevel.IDEMPOTENT' # = 2

---@class google_protobuf_descriptor_pb.MethodOptions
---@field deprecated boolean
---@field idempotency_level google_protobuf_descriptor_pb.MethodOptions.IdempotencyLevel
---@field uninterpreted_option google_protobuf_descriptor_pb.UninterpretedOption[]

---@class google_protobuf_descriptor_pb.UninterpretedOption.NamePart
---@field name_part string
---@field is_extension boolean

---@class google_protobuf_descriptor_pb.UninterpretedOption
---@field name google_protobuf_descriptor_pb.UninterpretedOption.NamePart[]
---@field identifier_value string
---@field positive_int_value number
---@field negative_int_value number
---@field double_value number
---@field string_value string
---@field aggregate_value string

---@class google_protobuf_descriptor_pb.SourceCodeInfo.Location
---@field path number[]
---@field span number[]
---@field leading_comments string
---@field trailing_comments string
---@field leading_detached_comments string[]

---@class google_protobuf_descriptor_pb.SourceCodeInfo
---@field location google_protobuf_descriptor_pb.SourceCodeInfo.Location[]

---@class google_protobuf_descriptor_pb.GeneratedCodeInfo.Annotation
---@field path number[]
---@field source_file string
---@field begin number
---@field end number

---@class google_protobuf_descriptor_pb.GeneratedCodeInfo
---@field annotation google_protobuf_descriptor_pb.GeneratedCodeInfo.Annotation[]

---@type fun():google_protobuf_descriptor_pb.FileDescriptorSet @New a '.google.protobuf.FileDescriptorSet'
google_protobuf_descriptor_pb.FileDescriptorSet = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[1])

---@type fun():google_protobuf_descriptor_pb.FileDescriptorProto @New a '.google.protobuf.FileDescriptorProto'
google_protobuf_descriptor_pb.FileDescriptorProto = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[2])

---@type fun():google_protobuf_descriptor_pb.DescriptorProto.ExtensionRange @New a '.google.protobuf.DescriptorProto.ExtensionRange'
google_protobuf_descriptor_pb.DescriptorProto.ExtensionRange = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[3].nested_type[1])

---@type fun():google_protobuf_descriptor_pb.DescriptorProto.ReservedRange @New a '.google.protobuf.DescriptorProto.ReservedRange'
google_protobuf_descriptor_pb.DescriptorProto.ReservedRange = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[3].nested_type[2])

---@type fun():google_protobuf_descriptor_pb.DescriptorProto @New a '.google.protobuf.DescriptorProto'
google_protobuf_descriptor_pb.DescriptorProto = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[3])

---@type fun():google_protobuf_descriptor_pb.ExtensionRangeOptions @New a '.google.protobuf.ExtensionRangeOptions'
google_protobuf_descriptor_pb.ExtensionRangeOptions = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[4])

google_protobuf_descriptor_pb.FieldDescriptorProto.Type = protobuf_reflect.Enum(google_protobuf_descriptor_pb_desc.message_type[5].enum_type[1])
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_DOUBLE = 1
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_FLOAT = 2
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT64 = 3
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_UINT64 = 4
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_INT32 = 5
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_FIXED64 = 6
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_FIXED32 = 7
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL = 8
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING = 9
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_GROUP = 10
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE = 11
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BYTES = 12
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_UINT32 = 13
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_ENUM = 14
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_SFIXED32 = 15
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_SFIXED64 = 16
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_SINT32 = 17
google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_SINT64 = 18

google_protobuf_descriptor_pb.FieldDescriptorProto.Label = protobuf_reflect.Enum(google_protobuf_descriptor_pb_desc.message_type[5].enum_type[2])
google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL = 1
google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REQUIRED = 2
google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED = 3

---@type fun():google_protobuf_descriptor_pb.FieldDescriptorProto @New a '.google.protobuf.FieldDescriptorProto'
google_protobuf_descriptor_pb.FieldDescriptorProto = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[5])

---@type fun():google_protobuf_descriptor_pb.OneofDescriptorProto @New a '.google.protobuf.OneofDescriptorProto'
google_protobuf_descriptor_pb.OneofDescriptorProto = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[6])

---@type fun():google_protobuf_descriptor_pb.EnumDescriptorProto.EnumReservedRange @New a '.google.protobuf.EnumDescriptorProto.EnumReservedRange'
google_protobuf_descriptor_pb.EnumDescriptorProto.EnumReservedRange = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[7].nested_type[1])

---@type fun():google_protobuf_descriptor_pb.EnumDescriptorProto @New a '.google.protobuf.EnumDescriptorProto'
google_protobuf_descriptor_pb.EnumDescriptorProto = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[7])

---@type fun():google_protobuf_descriptor_pb.EnumValueDescriptorProto @New a '.google.protobuf.EnumValueDescriptorProto'
google_protobuf_descriptor_pb.EnumValueDescriptorProto = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[8])

---@type fun():google_protobuf_descriptor_pb.ServiceDescriptorProto @New a '.google.protobuf.ServiceDescriptorProto'
google_protobuf_descriptor_pb.ServiceDescriptorProto = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[9])

---@type fun():google_protobuf_descriptor_pb.MethodDescriptorProto @New a '.google.protobuf.MethodDescriptorProto'
google_protobuf_descriptor_pb.MethodDescriptorProto = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[10])

google_protobuf_descriptor_pb.FileOptions.OptimizeMode = protobuf_reflect.Enum(google_protobuf_descriptor_pb_desc.message_type[11].enum_type[1])
google_protobuf_descriptor_pb.FileOptions.OptimizeMode.SPEED = 1
google_protobuf_descriptor_pb.FileOptions.OptimizeMode.CODE_SIZE = 2
google_protobuf_descriptor_pb.FileOptions.OptimizeMode.LITE_RUNTIME = 3

---@type fun():google_protobuf_descriptor_pb.FileOptions @New a '.google.protobuf.FileOptions'
google_protobuf_descriptor_pb.FileOptions = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[11])

---@type fun():google_protobuf_descriptor_pb.MessageOptions @New a '.google.protobuf.MessageOptions'
google_protobuf_descriptor_pb.MessageOptions = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[12])

google_protobuf_descriptor_pb.FieldOptions.CType = protobuf_reflect.Enum(google_protobuf_descriptor_pb_desc.message_type[13].enum_type[1])
google_protobuf_descriptor_pb.FieldOptions.CType.STRING = 0
google_protobuf_descriptor_pb.FieldOptions.CType.CORD = 1
google_protobuf_descriptor_pb.FieldOptions.CType.STRING_PIECE = 2

google_protobuf_descriptor_pb.FieldOptions.JSType = protobuf_reflect.Enum(google_protobuf_descriptor_pb_desc.message_type[13].enum_type[2])
google_protobuf_descriptor_pb.FieldOptions.JSType.JS_NORMAL = 0
google_protobuf_descriptor_pb.FieldOptions.JSType.JS_STRING = 1
google_protobuf_descriptor_pb.FieldOptions.JSType.JS_NUMBER = 2

---@type fun():google_protobuf_descriptor_pb.FieldOptions @New a '.google.protobuf.FieldOptions'
google_protobuf_descriptor_pb.FieldOptions = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[13])

---@type fun():google_protobuf_descriptor_pb.OneofOptions @New a '.google.protobuf.OneofOptions'
google_protobuf_descriptor_pb.OneofOptions = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[14])

---@type fun():google_protobuf_descriptor_pb.EnumOptions @New a '.google.protobuf.EnumOptions'
google_protobuf_descriptor_pb.EnumOptions = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[15])

---@type fun():google_protobuf_descriptor_pb.EnumValueOptions @New a '.google.protobuf.EnumValueOptions'
google_protobuf_descriptor_pb.EnumValueOptions = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[16])

---@type fun():google_protobuf_descriptor_pb.ServiceOptions @New a '.google.protobuf.ServiceOptions'
google_protobuf_descriptor_pb.ServiceOptions = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[17])

google_protobuf_descriptor_pb.MethodOptions.IdempotencyLevel = protobuf_reflect.Enum(google_protobuf_descriptor_pb_desc.message_type[18].enum_type[1])
google_protobuf_descriptor_pb.MethodOptions.IdempotencyLevel.IDEMPOTENCY_UNKNOWN = 0
google_protobuf_descriptor_pb.MethodOptions.IdempotencyLevel.NO_SIDE_EFFECTS = 1
google_protobuf_descriptor_pb.MethodOptions.IdempotencyLevel.IDEMPOTENT = 2

---@type fun():google_protobuf_descriptor_pb.MethodOptions @New a '.google.protobuf.MethodOptions'
google_protobuf_descriptor_pb.MethodOptions = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[18])

---@type fun():google_protobuf_descriptor_pb.UninterpretedOption.NamePart @New a '.google.protobuf.UninterpretedOption.NamePart'
google_protobuf_descriptor_pb.UninterpretedOption.NamePart = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[19].nested_type[1])

---@type fun():google_protobuf_descriptor_pb.UninterpretedOption @New a '.google.protobuf.UninterpretedOption'
google_protobuf_descriptor_pb.UninterpretedOption = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[19])

---@type fun():google_protobuf_descriptor_pb.SourceCodeInfo.Location @New a '.google.protobuf.SourceCodeInfo.Location'
google_protobuf_descriptor_pb.SourceCodeInfo.Location = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[20].nested_type[1])

---@type fun():google_protobuf_descriptor_pb.SourceCodeInfo @New a '.google.protobuf.SourceCodeInfo'
google_protobuf_descriptor_pb.SourceCodeInfo = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[20])

---@type fun():google_protobuf_descriptor_pb.GeneratedCodeInfo.Annotation @New a '.google.protobuf.GeneratedCodeInfo.Annotation'
google_protobuf_descriptor_pb.GeneratedCodeInfo.Annotation = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[21].nested_type[1])

---@type fun():google_protobuf_descriptor_pb.GeneratedCodeInfo @New a '.google.protobuf.GeneratedCodeInfo'
google_protobuf_descriptor_pb.GeneratedCodeInfo = protobuf_reflect.Message(google_protobuf_descriptor_pb_desc.message_type[21])


return google_protobuf_descriptor_pb
