--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('google.protobuf.duration_pb')

DURATION = protobuf.Descriptor();
DURATION_SECONDS_FIELD = protobuf.FieldDescriptor();
DURATION_NANOS_FIELD = protobuf.FieldDescriptor();

DURATION_SECONDS_FIELD.name = "seconds"
DURATION_SECONDS_FIELD.full_name = ".google.protobuf.Duration.seconds"
DURATION_SECONDS_FIELD.number = 1
DURATION_SECONDS_FIELD.index = 0
DURATION_SECONDS_FIELD.label = 1
DURATION_SECONDS_FIELD.has_default_value = false
DURATION_SECONDS_FIELD.default_value = 0
DURATION_SECONDS_FIELD.type = 3
DURATION_SECONDS_FIELD.cpp_type = 2

DURATION_NANOS_FIELD.name = "nanos"
DURATION_NANOS_FIELD.full_name = ".google.protobuf.Duration.nanos"
DURATION_NANOS_FIELD.number = 2
DURATION_NANOS_FIELD.index = 1
DURATION_NANOS_FIELD.label = 1
DURATION_NANOS_FIELD.has_default_value = false
DURATION_NANOS_FIELD.default_value = 0
DURATION_NANOS_FIELD.type = 5
DURATION_NANOS_FIELD.cpp_type = 1

DURATION.name = "Duration"
DURATION.full_name = ".google.protobuf.Duration"
DURATION.nested_types = {}
DURATION.enum_types = {}
DURATION.fields = {DURATION_SECONDS_FIELD, DURATION_NANOS_FIELD}
DURATION.is_extendable = false
DURATION.extensions = {}

Duration = protobuf.Message(DURATION)

