-- This file is generated by proto-gen-lua. DO NOT EDIT.
local google_protobuf_duration_pb = {}

google_protobuf_duration_pb.Duration = {
    __call__ = function ()
        local message = {
            seconds = 0,
            nanos = 0,
        }

        return message
    end,

}

return google_protobuf_duration_pb
