-- This file is generated by proto-gen-lua. DO NOT EDIT.
local google_protobuf_empty_pb = {}

google_protobuf_empty_pb.Empty = {
    __call__ = function ()
        local message = {}
        return message
    end
,
}

return google_protobuf_empty_pb
