-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local google_protobuf_empty_pb_desc = require "google.protobuf.empty_pb_desc"

local google_protobuf_empty_pb = {}

---@class google_protobuf_empty_pb.Empty

---@type fun():google_protobuf_empty_pb.Empty @New a '.google.protobuf.Empty'
google_protobuf_empty_pb.Empty = protobuf_reflect.Message(google_protobuf_empty_pb_desc.message_type[1])


return google_protobuf_empty_pb
