-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local google_protobuf_empty_pb_desc = require "google.protobuf.empty_pb_desc"

local google_protobuf_empty_pb = {}

---@class google_protobuf_empty_pb.Empty : protobuf.Message

---@type fun():google_protobuf_empty_pb.Empty
google_protobuf_empty_pb.Empty = protobuf.Message(google_protobuf_empty_pb_desc.message_type[1])
google_protobuf_empty_pb.Empty._FullName = ".google.protobuf.Empty"
google_protobuf_empty_pb.Empty._Descriptor = "google_protobuf_empty_pb_desc.message_type[1]"
registry.RegistMessage(google_protobuf_empty_pb.Empty)


return google_protobuf_empty_pb
