-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local google_protobuf_field_mask_pb_desc = require "google.protobuf.field_mask_pb_desc"

local google_protobuf_field_mask_pb = {}

---@class google_protobuf_field_mask_pb.FieldMask : protobuf.Message
---@field paths string[]

---@type fun():google_protobuf_field_mask_pb.FieldMask
google_protobuf_field_mask_pb.FieldMask = protobuf.Message(google_protobuf_field_mask_pb_desc.message_type[1])
google_protobuf_field_mask_pb.FieldMask._FullName = ".google.protobuf.FieldMask"
google_protobuf_field_mask_pb.FieldMask._Descriptor = "google_protobuf_field_mask_pb_desc.message_type[1]"
registry.RegistMessage(google_protobuf_field_mask_pb.FieldMask)


return google_protobuf_field_mask_pb
