-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local google_protobuf_field_mask_pb = {}

google_protobuf_field_mask_pb.FieldMask = setmetatable({}, {
    __call = function ()
        local default = {
            paths = {},
        }
        return setmetatable(default, google_protobuf_field_mask_pb.FieldMask)
    end
})

----------------- Descriptor -----------------

local google_protobuf_descriptor_pb = require "google/protobuf/descriptor_pb"
google_protobuf_field_mask_pb.FieldMask.Descriptor = {
    name = ".google.protobuf.FieldMask",
    field = {
        paths = {
            name = ".google.protobuf.FieldMask.paths",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_field_mask_pb.Descriptor = {
    name = "google/protobuf/field_mask.proto",
    package = "google.protobuf",
    message_type = {
        google_protobuf_field_mask_pb.FieldMask.Descriptor,
    },
}
return google_protobuf_field_mask_pb
