-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local google_protobuf_field_mask_pb_desc = require "google.protobuf.field_mask_pb_desc"

local google_protobuf_field_mask_pb = {}

---@class google_protobuf_field_mask_pb.FieldMask
---@field paths string[]

---@type fun():google_protobuf_field_mask_pb.FieldMask @New a '.google.protobuf.FieldMask'
google_protobuf_field_mask_pb.FieldMask = protobuf_reflect.Message(google_protobuf_field_mask_pb_desc.message_type[1])


return google_protobuf_field_mask_pb
