-- This file is generated by proto-gen-lua. DO NOT EDIT.
local google_protobuf_source_context_pb = {}

google_protobuf_source_context_pb.SourceContext = {
    __call__ = function ()
        local message = {
            file_name = "",
        }

        return message
    end
,
}

return google_protobuf_source_context_pb
