-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local google_protobuf_source_context_pb_desc = require "google.protobuf.source_context_pb_desc"

local google_protobuf_source_context_pb = {}

---@class google_protobuf_source_context_pb.SourceContext
---@field file_name string

---@type fun():google_protobuf_source_context_pb.SourceContext @New a '.google.protobuf.SourceContext'
google_protobuf_source_context_pb.SourceContext = protobuf_reflect.Message(google_protobuf_source_context_pb_desc.message_type[1])


return google_protobuf_source_context_pb
