-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

return {
    name = [[google/protobuf/source_context.proto]],
    package = [[google.protobuf]],
    message_type = {
        {
            name = [[SourceContext]],
            field = {
                {
                    name = [[file_name]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_STRING]],
                    json_name = [[fileName]],
                },
            },
        },
    },
    options = {
        java_package = [[com.google.protobuf]],
        java_outer_classname = [[SourceContextProto]],
        java_multiple_files = true,
        go_package = [[google.golang.org/protobuf/types/known/sourcecontextpb]],
        objc_class_prefix = [[GPB]],
        csharp_namespace = [[Google.Protobuf.WellKnownTypes]],
    },
    syntax = [[proto3]],
}