--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('google.protobuf.source_context_pb')

SOURCECONTEXT = protobuf.Descriptor();
SOURCECONTEXT_FILE_NAME_FIELD = protobuf.FieldDescriptor();

SOURCECONTEXT_FILE_NAME_FIELD.name = "file_name"
SOURCECONTEXT_FILE_NAME_FIELD.full_name = ".google.protobuf.SourceContext.file_name"
SOURCECONTEXT_FILE_NAME_FIELD.number = 1
SOURCECONTEXT_FILE_NAME_FIELD.index = 0
SOURCECONTEXT_FILE_NAME_FIELD.label = 1
SOURCECONTEXT_FILE_NAME_FIELD.has_default_value = false
SOURCECONTEXT_FILE_NAME_FIELD.default_value = ""
SOURCECONTEXT_FILE_NAME_FIELD.type = 9
SOURCECONTEXT_FILE_NAME_FIELD.cpp_type = 9

SOURCECONTEXT.name = "SourceContext"
SOURCECONTEXT.full_name = ".google.protobuf.SourceContext"
SOURCECONTEXT.nested_types = {}
SOURCECONTEXT.enum_types = {}
SOURCECONTEXT.fields = {SOURCECONTEXT_FILE_NAME_FIELD}
SOURCECONTEXT.is_extendable = false
SOURCECONTEXT.extensions = {}

SourceContext = protobuf.Message(SOURCECONTEXT)

