-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local google_protobuf_struct_pb_desc = require "google.protobuf.struct_pb_desc"

local google_protobuf_struct_pb = {}

---@alias google_protobuf_struct_pb.NullValue
---| 'google_protobuf_struct_pb.NullValue.NULL_VALUE' # = 0

---@class google_protobuf_struct_pb.Struct.FieldsEntry
---@field key string
---@field value google_protobuf_struct_pb.Value

---@class google_protobuf_struct_pb.Struct
---@field fields google_protobuf_struct_pb.Struct.FieldsEntry[]

---@class google_protobuf_struct_pb.Value
---@field null_value google_protobuf_struct_pb.NullValue
---@field number_value number
---@field string_value string
---@field bool_value boolean
---@field struct_value google_protobuf_struct_pb.Struct
---@field list_value google_protobuf_struct_pb.ListValue

---@class google_protobuf_struct_pb.ListValue
---@field values google_protobuf_struct_pb.Value[]

google_protobuf_struct_pb.NullValue = protobuf_reflect.Enum(google_protobuf_struct_pb_desc.enum_type[1])
google_protobuf_struct_pb.NullValue.NULL_VALUE = 0

---@type fun():google_protobuf_struct_pb.Struct.FieldsEntry @New a '.google.protobuf.Struct.FieldsEntry'
google_protobuf_struct_pb.Struct.FieldsEntry = protobuf_reflect.Message(google_protobuf_struct_pb_desc.message_type[1].nested_type[1])

---@type fun():google_protobuf_struct_pb.Struct @New a '.google.protobuf.Struct'
google_protobuf_struct_pb.Struct = protobuf_reflect.Message(google_protobuf_struct_pb_desc.message_type[1])

---@type fun():google_protobuf_struct_pb.Value @New a '.google.protobuf.Value'
google_protobuf_struct_pb.Value = protobuf_reflect.Message(google_protobuf_struct_pb_desc.message_type[2])

---@type fun():google_protobuf_struct_pb.ListValue @New a '.google.protobuf.ListValue'
google_protobuf_struct_pb.ListValue = protobuf_reflect.Message(google_protobuf_struct_pb_desc.message_type[3])


return google_protobuf_struct_pb
