-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local google_protobuf_struct_pb = {}

google_protobuf_struct_pb.NullValue = {
    NULL_VALUE = 0,
}

google_protobuf_struct_pb.Struct = setmetatable({}, {
    __call = function ()
        local default = {
            fields = {},
        }
        return setmetatable(default, google_protobuf_struct_pb.Struct)
    end
})

google_protobuf_struct_pb.Struct.FieldsEntry = setmetatable({}, {
    __call = function ()
        local default = {
            key = "",
            value = {},
        }
        return setmetatable(default, google_protobuf_struct_pb.Struct.FieldsEntry)
    end
})

google_protobuf_struct_pb.Value = setmetatable({}, {
    __call = function ()
        local default = {
            null_value = google_protobuf_struct_pb.NullValue.NULL_VALUE,
            number_value = 0.0,
            string_value = "",
            bool_value = false,
            struct_value = {},
            list_value = {},
        }
        return setmetatable(default, google_protobuf_struct_pb.Value)
    end
})

google_protobuf_struct_pb.ListValue = setmetatable({}, {
    __call = function ()
        local default = {
            values = {},
        }
        return setmetatable(default, google_protobuf_struct_pb.ListValue)
    end
})

----------------- Descriptor -----------------

local google_protobuf_descriptor_pb = require "google/protobuf/descriptor_pb"
google_protobuf_struct_pb.NullValue.Descriptor = {
    name = ".google.protobuf.NullValue",
}
google_protobuf_struct_pb.Struct.FieldsEntry.Descriptor = {
    name = ".google.protobuf.Struct.FieldsEntry",
    field = {
        key = {
            name = ".google.protobuf.Struct.FieldsEntry.key",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        value = {
            name = ".google.protobuf.Struct.FieldsEntry.value",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.Value",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_struct_pb.Struct.Descriptor = {
    name = ".google.protobuf.Struct",
    field = {
        fields = {
            name = ".google.protobuf.Struct.fields",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.Struct.FieldsEntry",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_struct_pb.Value.Descriptor = {
    name = ".google.protobuf.Value",
    field = {
        null_value = {
            name = ".google.protobuf.Value.null_value",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_ENUM,
            type_name = ".google.protobuf.NullValue",
            options = {
                packed = false,
            }
        },
        number_value = {
            name = ".google.protobuf.Value.number_value",
            number = 2,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_DOUBLE,
            options = {
                packed = false,
            }
        },
        string_value = {
            name = ".google.protobuf.Value.string_value",
            number = 3,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_STRING,
            options = {
                packed = false,
            }
        },
        bool_value = {
            name = ".google.protobuf.Value.bool_value",
            number = 4,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_BOOL,
            options = {
                packed = false,
            }
        },
        struct_value = {
            name = ".google.protobuf.Value.struct_value",
            number = 5,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.Struct",
            options = {
                packed = false,
            }
        },
        list_value = {
            name = ".google.protobuf.Value.list_value",
            number = 6,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_OPTIONAL,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.ListValue",
            options = {
                packed = false,
            }
        },
    },
    oneof_decl = {
        "kind",
    },
}
google_protobuf_struct_pb.ListValue.Descriptor = {
    name = ".google.protobuf.ListValue",
    field = {
        values = {
            name = ".google.protobuf.ListValue.values",
            number = 1,
            label = google_protobuf_descriptor_pb.FieldDescriptorProto.Label.LABEL_REPEATED,
            type = google_protobuf_descriptor_pb.FieldDescriptorProto.Type.TYPE_MESSAGE,
            type_name = ".google.protobuf.Value",
            options = {
                packed = false,
            }
        },
    },
}
google_protobuf_struct_pb.Descriptor = {
    name = "google/protobuf/struct.proto",
    package = "google.protobuf",
    message_type = {
        google_protobuf_struct_pb.Struct.Descriptor,
        google_protobuf_struct_pb.Value.Descriptor,
        google_protobuf_struct_pb.ListValue.Descriptor,
    },
    enum_type = {
        google_protobuf_struct_pb.NullValue.Descriptor,
    },
}
return google_protobuf_struct_pb
