-- This file is generated by proto-gen-lua. DO NOT EDIT.
local google_protobuf_timestamp_pb = {}

google_protobuf_timestamp_pb.Timestamp = {
    __call__ = function ()
        local message = {
            seconds = 0,
            nanos = 0,
        }

        return message
    end,

}

return google_protobuf_timestamp_pb
