--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('google.protobuf.timestamp_pb')

TIMESTAMP = protobuf.Descriptor();
TIMESTAMP_SECONDS_FIELD = protobuf.FieldDescriptor();
TIMESTAMP_NANOS_FIELD = protobuf.FieldDescriptor();

TIMESTAMP_SECONDS_FIELD.name = "seconds"
TIMESTAMP_SECONDS_FIELD.full_name = ".google.protobuf.Timestamp.seconds"
TIMESTAMP_SECONDS_FIELD.number = 1
TIMESTAMP_SECONDS_FIELD.index = 0
TIMESTAMP_SECONDS_FIELD.label = 1
TIMESTAMP_SECONDS_FIELD.has_default_value = false
TIMESTAMP_SECONDS_FIELD.default_value = 0
TIMESTAMP_SECONDS_FIELD.type = 3
TIMESTAMP_SECONDS_FIELD.cpp_type = 2

TIMESTAMP_NANOS_FIELD.name = "nanos"
TIMESTAMP_NANOS_FIELD.full_name = ".google.protobuf.Timestamp.nanos"
TIMESTAMP_NANOS_FIELD.number = 2
TIMESTAMP_NANOS_FIELD.index = 1
TIMESTAMP_NANOS_FIELD.label = 1
TIMESTAMP_NANOS_FIELD.has_default_value = false
TIMESTAMP_NANOS_FIELD.default_value = 0
TIMESTAMP_NANOS_FIELD.type = 5
TIMESTAMP_NANOS_FIELD.cpp_type = 1

TIMESTAMP.name = "Timestamp"
TIMESTAMP.full_name = ".google.protobuf.Timestamp"
TIMESTAMP.nested_types = {}
TIMESTAMP.enum_types = {}
TIMESTAMP.fields = {TIMESTAMP_SECONDS_FIELD, TIMESTAMP_NANOS_FIELD}
TIMESTAMP.is_extendable = false
TIMESTAMP.extensions = {}

Timestamp = protobuf.Message(TIMESTAMP)

