-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

return {
    name = [[google/protobuf/type.proto]],
    package = [[google.protobuf]],
    dependency = {
        [[google/protobuf/any.proto]],
        [[google/protobuf/source_context.proto]],
    },
    message_type = {
        {
            name = [[Type]],
            field = {
                {
                    name = [[name]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_STRING]],
                    json_name = [[name]],
                },
                {
                    name = [[fields]],
                    number = 2,
                    label = [[LABEL_REPEATED]],
                    type = [[TYPE_MESSAGE]],
                    type_name = [[.google.protobuf.Field]],
                    json_name = [[fields]],
                },
                {
                    name = [[oneofs]],
                    number = 3,
                    label = [[LABEL_REPEATED]],
                    type = [[TYPE_STRING]],
                    json_name = [[oneofs]],
                },
                {
                    name = [[options]],
                    number = 4,
                    label = [[LABEL_REPEATED]],
                    type = [[TYPE_MESSAGE]],
                    type_name = [[.google.protobuf.Option]],
                    json_name = [[options]],
                },
                {
                    name = [[source_context]],
                    number = 5,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_MESSAGE]],
                    type_name = [[.google.protobuf.SourceContext]],
                    json_name = [[sourceContext]],
                },
                {
                    name = [[syntax]],
                    number = 6,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_ENUM]],
                    type_name = [[.google.protobuf.Syntax]],
                    json_name = [[syntax]],
                },
            },
        },
        {
            name = [[Field]],
            field = {
                {
                    name = [[kind]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_ENUM]],
                    type_name = [[.google.protobuf.Field.Kind]],
                    json_name = [[kind]],
                },
                {
                    name = [[cardinality]],
                    number = 2,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_ENUM]],
                    type_name = [[.google.protobuf.Field.Cardinality]],
                    json_name = [[cardinality]],
                },
                {
                    name = [[number]],
                    number = 3,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_INT32]],
                    json_name = [[number]],
                },
                {
                    name = [[name]],
                    number = 4,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_STRING]],
                    json_name = [[name]],
                },
                {
                    name = [[type_url]],
                    number = 6,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_STRING]],
                    json_name = [[typeUrl]],
                },
                {
                    name = [[oneof_index]],
                    number = 7,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_INT32]],
                    json_name = [[oneofIndex]],
                },
                {
                    name = [[packed]],
                    number = 8,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_BOOL]],
                    json_name = [[packed]],
                },
                {
                    name = [[options]],
                    number = 9,
                    label = [[LABEL_REPEATED]],
                    type = [[TYPE_MESSAGE]],
                    type_name = [[.google.protobuf.Option]],
                    json_name = [[options]],
                },
                {
                    name = [[json_name]],
                    number = 10,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_STRING]],
                    json_name = [[jsonName]],
                },
                {
                    name = [[default_value]],
                    number = 11,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_STRING]],
                    json_name = [[defaultValue]],
                },
            },
            enum_type = {
                {
                    name = [[Kind]],
                    value = {
                        {
                            name = [[TYPE_UNKNOWN]],
                            number = 0,
                        },
                        {
                            name = [[TYPE_DOUBLE]],
                            number = 1,
                        },
                        {
                            name = [[TYPE_FLOAT]],
                            number = 2,
                        },
                        {
                            name = [[TYPE_INT64]],
                            number = 3,
                        },
                        {
                            name = [[TYPE_UINT64]],
                            number = 4,
                        },
                        {
                            name = [[TYPE_INT32]],
                            number = 5,
                        },
                        {
                            name = [[TYPE_FIXED64]],
                            number = 6,
                        },
                        {
                            name = [[TYPE_FIXED32]],
                            number = 7,
                        },
                        {
                            name = [[TYPE_BOOL]],
                            number = 8,
                        },
                        {
                            name = [[TYPE_STRING]],
                            number = 9,
                        },
                        {
                            name = [[TYPE_GROUP]],
                            number = 10,
                        },
                        {
                            name = [[TYPE_MESSAGE]],
                            number = 11,
                        },
                        {
                            name = [[TYPE_BYTES]],
                            number = 12,
                        },
                        {
                            name = [[TYPE_UINT32]],
                            number = 13,
                        },
                        {
                            name = [[TYPE_ENUM]],
                            number = 14,
                        },
                        {
                            name = [[TYPE_SFIXED32]],
                            number = 15,
                        },
                        {
                            name = [[TYPE_SFIXED64]],
                            number = 16,
                        },
                        {
                            name = [[TYPE_SINT32]],
                            number = 17,
                        },
                        {
                            name = [[TYPE_SINT64]],
                            number = 18,
                        },
                    },
                },
                {
                    name = [[Cardinality]],
                    value = {
                        {
                            name = [[CARDINALITY_UNKNOWN]],
                            number = 0,
                        },
                        {
                            name = [[CARDINALITY_OPTIONAL]],
                            number = 1,
                        },
                        {
                            name = [[CARDINALITY_REQUIRED]],
                            number = 2,
                        },
                        {
                            name = [[CARDINALITY_REPEATED]],
                            number = 3,
                        },
                    },
                },
            },
        },
        {
            name = [[Enum]],
            field = {
                {
                    name = [[name]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_STRING]],
                    json_name = [[name]],
                },
                {
                    name = [[enumvalue]],
                    number = 2,
                    label = [[LABEL_REPEATED]],
                    type = [[TYPE_MESSAGE]],
                    type_name = [[.google.protobuf.EnumValue]],
                    json_name = [[enumvalue]],
                },
                {
                    name = [[options]],
                    number = 3,
                    label = [[LABEL_REPEATED]],
                    type = [[TYPE_MESSAGE]],
                    type_name = [[.google.protobuf.Option]],
                    json_name = [[options]],
                },
                {
                    name = [[source_context]],
                    number = 4,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_MESSAGE]],
                    type_name = [[.google.protobuf.SourceContext]],
                    json_name = [[sourceContext]],
                },
                {
                    name = [[syntax]],
                    number = 5,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_ENUM]],
                    type_name = [[.google.protobuf.Syntax]],
                    json_name = [[syntax]],
                },
            },
        },
        {
            name = [[EnumValue]],
            field = {
                {
                    name = [[name]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_STRING]],
                    json_name = [[name]],
                },
                {
                    name = [[number]],
                    number = 2,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_INT32]],
                    json_name = [[number]],
                },
                {
                    name = [[options]],
                    number = 3,
                    label = [[LABEL_REPEATED]],
                    type = [[TYPE_MESSAGE]],
                    type_name = [[.google.protobuf.Option]],
                    json_name = [[options]],
                },
            },
        },
        {
            name = [[Option]],
            field = {
                {
                    name = [[name]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_STRING]],
                    json_name = [[name]],
                },
                {
                    name = [[value]],
                    number = 2,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_MESSAGE]],
                    type_name = [[.google.protobuf.Any]],
                    json_name = [[value]],
                },
            },
        },
    },
    enum_type = {
        {
            name = [[Syntax]],
            value = {
                {
                    name = [[SYNTAX_PROTO2]],
                    number = 0,
                },
                {
                    name = [[SYNTAX_PROTO3]],
                    number = 1,
                },
            },
        },
    },
    options = {
        java_package = [[com.google.protobuf]],
        java_outer_classname = [[TypeProto]],
        java_multiple_files = true,
        go_package = [[google.golang.org/protobuf/types/known/typepb]],
        cc_enable_arenas = true,
        objc_class_prefix = [[GPB]],
        csharp_namespace = [[Google.Protobuf.WellKnownTypes]],
    },
    syntax = [[proto3]],
}