-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"

local google_protobuf_any_pb = require "google.protobuf.any_pb"
local google_protobuf_source_context_pb = require "google.protobuf.source_context_pb"

local google_protobuf_type_pb_desc = require "google.protobuf.type_pb_desc"

local google_protobuf_type_pb = {}

---@alias google_protobuf_type_pb.Syntax
---| 'google_protobuf_type_pb.Syntax.SYNTAX_PROTO2' # = 0
---| 'google_protobuf_type_pb.Syntax.SYNTAX_PROTO3' # = 1

---@class google_protobuf_type_pb.Type
---@field name string
---@field fields google_protobuf_type_pb.Field[]
---@field oneofs string[]
---@field options google_protobuf_type_pb.Option[]
---@field source_context google_protobuf_source_context_pb.SourceContext
---@field syntax google_protobuf_type_pb.Syntax

---@alias google_protobuf_type_pb.Field.Kind
---| 'google_protobuf_type_pb.Field.Kind.TYPE_UNKNOWN' # = 0
---| 'google_protobuf_type_pb.Field.Kind.TYPE_DOUBLE' # = 1
---| 'google_protobuf_type_pb.Field.Kind.TYPE_FLOAT' # = 2
---| 'google_protobuf_type_pb.Field.Kind.TYPE_INT64' # = 3
---| 'google_protobuf_type_pb.Field.Kind.TYPE_UINT64' # = 4
---| 'google_protobuf_type_pb.Field.Kind.TYPE_INT32' # = 5
---| 'google_protobuf_type_pb.Field.Kind.TYPE_FIXED64' # = 6
---| 'google_protobuf_type_pb.Field.Kind.TYPE_FIXED32' # = 7
---| 'google_protobuf_type_pb.Field.Kind.TYPE_BOOL' # = 8
---| 'google_protobuf_type_pb.Field.Kind.TYPE_STRING' # = 9
---| 'google_protobuf_type_pb.Field.Kind.TYPE_GROUP' # = 10
---| 'google_protobuf_type_pb.Field.Kind.TYPE_MESSAGE' # = 11
---| 'google_protobuf_type_pb.Field.Kind.TYPE_BYTES' # = 12
---| 'google_protobuf_type_pb.Field.Kind.TYPE_UINT32' # = 13
---| 'google_protobuf_type_pb.Field.Kind.TYPE_ENUM' # = 14
---| 'google_protobuf_type_pb.Field.Kind.TYPE_SFIXED32' # = 15
---| 'google_protobuf_type_pb.Field.Kind.TYPE_SFIXED64' # = 16
---| 'google_protobuf_type_pb.Field.Kind.TYPE_SINT32' # = 17
---| 'google_protobuf_type_pb.Field.Kind.TYPE_SINT64' # = 18

---@alias google_protobuf_type_pb.Field.Cardinality
---| 'google_protobuf_type_pb.Field.Cardinality.CARDINALITY_UNKNOWN' # = 0
---| 'google_protobuf_type_pb.Field.Cardinality.CARDINALITY_OPTIONAL' # = 1
---| 'google_protobuf_type_pb.Field.Cardinality.CARDINALITY_REQUIRED' # = 2
---| 'google_protobuf_type_pb.Field.Cardinality.CARDINALITY_REPEATED' # = 3

---@class google_protobuf_type_pb.Field
---@field kind google_protobuf_type_pb.Field.Kind
---@field cardinality google_protobuf_type_pb.Field.Cardinality
---@field number number
---@field name string
---@field type_url string
---@field oneof_index number
---@field packed boolean
---@field options google_protobuf_type_pb.Option[]
---@field json_name string
---@field default_value string

---@class google_protobuf_type_pb.Enum
---@field name string
---@field enumvalue google_protobuf_type_pb.EnumValue[]
---@field options google_protobuf_type_pb.Option[]
---@field source_context google_protobuf_source_context_pb.SourceContext
---@field syntax google_protobuf_type_pb.Syntax

---@class google_protobuf_type_pb.EnumValue
---@field name string
---@field number number
---@field options google_protobuf_type_pb.Option[]

---@class google_protobuf_type_pb.Option
---@field name string
---@field value google_protobuf_any_pb.Any

google_protobuf_type_pb.Syntax = protobuf_reflect.Enum(google_protobuf_type_pb_desc.enum_type[1])
google_protobuf_type_pb.Syntax.SYNTAX_PROTO2 = 0
google_protobuf_type_pb.Syntax.SYNTAX_PROTO3 = 1

---@type fun():google_protobuf_type_pb.Type @New a '.google.protobuf.Type'
google_protobuf_type_pb.Type = protobuf_reflect.Message(google_protobuf_type_pb_desc.message_type[1])

google_protobuf_type_pb.Field.Kind = protobuf_reflect.Enum(google_protobuf_type_pb_desc.message_type[2].enum_type[1])
google_protobuf_type_pb.Field.Kind.TYPE_UNKNOWN = 0
google_protobuf_type_pb.Field.Kind.TYPE_DOUBLE = 1
google_protobuf_type_pb.Field.Kind.TYPE_FLOAT = 2
google_protobuf_type_pb.Field.Kind.TYPE_INT64 = 3
google_protobuf_type_pb.Field.Kind.TYPE_UINT64 = 4
google_protobuf_type_pb.Field.Kind.TYPE_INT32 = 5
google_protobuf_type_pb.Field.Kind.TYPE_FIXED64 = 6
google_protobuf_type_pb.Field.Kind.TYPE_FIXED32 = 7
google_protobuf_type_pb.Field.Kind.TYPE_BOOL = 8
google_protobuf_type_pb.Field.Kind.TYPE_STRING = 9
google_protobuf_type_pb.Field.Kind.TYPE_GROUP = 10
google_protobuf_type_pb.Field.Kind.TYPE_MESSAGE = 11
google_protobuf_type_pb.Field.Kind.TYPE_BYTES = 12
google_protobuf_type_pb.Field.Kind.TYPE_UINT32 = 13
google_protobuf_type_pb.Field.Kind.TYPE_ENUM = 14
google_protobuf_type_pb.Field.Kind.TYPE_SFIXED32 = 15
google_protobuf_type_pb.Field.Kind.TYPE_SFIXED64 = 16
google_protobuf_type_pb.Field.Kind.TYPE_SINT32 = 17
google_protobuf_type_pb.Field.Kind.TYPE_SINT64 = 18

google_protobuf_type_pb.Field.Cardinality = protobuf_reflect.Enum(google_protobuf_type_pb_desc.message_type[2].enum_type[2])
google_protobuf_type_pb.Field.Cardinality.CARDINALITY_UNKNOWN = 0
google_protobuf_type_pb.Field.Cardinality.CARDINALITY_OPTIONAL = 1
google_protobuf_type_pb.Field.Cardinality.CARDINALITY_REQUIRED = 2
google_protobuf_type_pb.Field.Cardinality.CARDINALITY_REPEATED = 3

---@type fun():google_protobuf_type_pb.Field @New a '.google.protobuf.Field'
google_protobuf_type_pb.Field = protobuf_reflect.Message(google_protobuf_type_pb_desc.message_type[2])

---@type fun():google_protobuf_type_pb.Enum @New a '.google.protobuf.Enum'
google_protobuf_type_pb.Enum = protobuf_reflect.Message(google_protobuf_type_pb_desc.message_type[3])

---@type fun():google_protobuf_type_pb.EnumValue @New a '.google.protobuf.EnumValue'
google_protobuf_type_pb.EnumValue = protobuf_reflect.Message(google_protobuf_type_pb_desc.message_type[4])

---@type fun():google_protobuf_type_pb.Option @New a '.google.protobuf.Option'
google_protobuf_type_pb.Option = protobuf_reflect.Message(google_protobuf_type_pb_desc.message_type[5])


return google_protobuf_type_pb
