-- This file is generated by proto-gen-lua. DO NOT EDIT.
local google_protobuf_any_pb = require "google.protobuf.any_pb"
local google_protobuf_source_context_pb = require "google.protobuf.source_context_pb"
local google_protobuf_type_pb = {}

google_protobuf_type_pb.Syntax = {
    SYNTAX_PROTO2 = 0,
    SYNTAX_PROTO3 = 1,
}

google_protobuf_type_pb.Type = {
    __call__ = function ()
        local message = {
            name = "",
            fields = {},
            oneofs = {},
            options = {},
            source_context = google_protobuf_source_context_pb.SourceContext(),
            syntax = 0,
        }

        return message
    end,

}

google_protobuf_type_pb.Field = {
    Kind = {
        TYPE_UNKNOWN = 0,
        TYPE_DOUBLE = 1,
        TYPE_FLOAT = 2,
        TYPE_INT64 = 3,
        TYPE_UINT64 = 4,
        TYPE_INT32 = 5,
        TYPE_FIXED64 = 6,
        TYPE_FIXED32 = 7,
        TYPE_BOOL = 8,
        TYPE_STRING = 9,
        TYPE_GROUP = 10,
        TYPE_MESSAGE = 11,
        TYPE_BYTES = 12,
        TYPE_UINT32 = 13,
        TYPE_ENUM = 14,
        TYPE_SFIXED32 = 15,
        TYPE_SFIXED64 = 16,
        TYPE_SINT32 = 17,
        TYPE_SINT64 = 18,
    },

    Cardinality = {
        CARDINALITY_UNKNOWN = 0,
        CARDINALITY_OPTIONAL = 1,
        CARDINALITY_REQUIRED = 2,
        CARDINALITY_REPEATED = 3,
    },

    __call__ = function ()
        local message = {
            kind = 0,
            cardinality = 0,
            number = 0,
            name = "",
            type_url = "",
            oneof_index = 0,
            packed = false,
            options = {},
            json_name = "",
            default_value = "",
        }

        return message
    end,

}

google_protobuf_type_pb.Enum = {
    __call__ = function ()
        local message = {
            name = "",
            enumvalue = {},
            options = {},
            source_context = google_protobuf_source_context_pb.SourceContext(),
            syntax = 0,
        }

        return message
    end,

}

google_protobuf_type_pb.EnumValue = {
    __call__ = function ()
        local message = {
            name = "",
            number = 0,
            options = {},
        }

        return message
    end,

}

google_protobuf_type_pb.Option = {
    __call__ = function ()
        local message = {
            name = "",
            value = google_protobuf_any_pb.Any(),
        }

        return message
    end,

}

return google_protobuf_type_pb
