-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local google_protobuf_wrappers_pb_desc = require "google.protobuf.wrappers_pb_desc"

local google_protobuf_wrappers_pb = {}

---@class google_protobuf_wrappers_pb.DoubleValue
---@field value number

---@class google_protobuf_wrappers_pb.FloatValue
---@field value number

---@class google_protobuf_wrappers_pb.Int64Value
---@field value number

---@class google_protobuf_wrappers_pb.UInt64Value
---@field value number

---@class google_protobuf_wrappers_pb.Int32Value
---@field value number

---@class google_protobuf_wrappers_pb.UInt32Value
---@field value number

---@class google_protobuf_wrappers_pb.BoolValue
---@field value boolean

---@class google_protobuf_wrappers_pb.StringValue
---@field value string

---@class google_protobuf_wrappers_pb.BytesValue
---@field value string

---@type fun():google_protobuf_wrappers_pb.DoubleValue @New a '.google.protobuf.DoubleValue'
google_protobuf_wrappers_pb.DoubleValue = protobuf_reflect.Message(google_protobuf_wrappers_pb_desc.message_type[1])

---@type fun():google_protobuf_wrappers_pb.FloatValue @New a '.google.protobuf.FloatValue'
google_protobuf_wrappers_pb.FloatValue = protobuf_reflect.Message(google_protobuf_wrappers_pb_desc.message_type[2])

---@type fun():google_protobuf_wrappers_pb.Int64Value @New a '.google.protobuf.Int64Value'
google_protobuf_wrappers_pb.Int64Value = protobuf_reflect.Message(google_protobuf_wrappers_pb_desc.message_type[3])

---@type fun():google_protobuf_wrappers_pb.UInt64Value @New a '.google.protobuf.UInt64Value'
google_protobuf_wrappers_pb.UInt64Value = protobuf_reflect.Message(google_protobuf_wrappers_pb_desc.message_type[4])

---@type fun():google_protobuf_wrappers_pb.Int32Value @New a '.google.protobuf.Int32Value'
google_protobuf_wrappers_pb.Int32Value = protobuf_reflect.Message(google_protobuf_wrappers_pb_desc.message_type[5])

---@type fun():google_protobuf_wrappers_pb.UInt32Value @New a '.google.protobuf.UInt32Value'
google_protobuf_wrappers_pb.UInt32Value = protobuf_reflect.Message(google_protobuf_wrappers_pb_desc.message_type[6])

---@type fun():google_protobuf_wrappers_pb.BoolValue @New a '.google.protobuf.BoolValue'
google_protobuf_wrappers_pb.BoolValue = protobuf_reflect.Message(google_protobuf_wrappers_pb_desc.message_type[7])

---@type fun():google_protobuf_wrappers_pb.StringValue @New a '.google.protobuf.StringValue'
google_protobuf_wrappers_pb.StringValue = protobuf_reflect.Message(google_protobuf_wrappers_pb_desc.message_type[8])

---@type fun():google_protobuf_wrappers_pb.BytesValue @New a '.google.protobuf.BytesValue'
google_protobuf_wrappers_pb.BytesValue = protobuf_reflect.Message(google_protobuf_wrappers_pb_desc.message_type[9])


return google_protobuf_wrappers_pb
