-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

return {
    name = [[google/protobuf/wrappers.proto]],
    package = [[google.protobuf]],
    message_type = {
        {
            name = [[DoubleValue]],
            field = {
                {
                    name = [[value]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_DOUBLE]],
                    json_name = [[value]],
                },
            },
        },
        {
            name = [[FloatValue]],
            field = {
                {
                    name = [[value]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_FLOAT]],
                    json_name = [[value]],
                },
            },
        },
        {
            name = [[Int64Value]],
            field = {
                {
                    name = [[value]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_INT64]],
                    json_name = [[value]],
                },
            },
        },
        {
            name = [[UInt64Value]],
            field = {
                {
                    name = [[value]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_UINT64]],
                    json_name = [[value]],
                },
            },
        },
        {
            name = [[Int32Value]],
            field = {
                {
                    name = [[value]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_INT32]],
                    json_name = [[value]],
                },
            },
        },
        {
            name = [[UInt32Value]],
            field = {
                {
                    name = [[value]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_UINT32]],
                    json_name = [[value]],
                },
            },
        },
        {
            name = [[BoolValue]],
            field = {
                {
                    name = [[value]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_BOOL]],
                    json_name = [[value]],
                },
            },
        },
        {
            name = [[StringValue]],
            field = {
                {
                    name = [[value]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_STRING]],
                    json_name = [[value]],
                },
            },
        },
        {
            name = [[BytesValue]],
            field = {
                {
                    name = [[value]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_BYTES]],
                    json_name = [[value]],
                },
            },
        },
    },
    options = {
        java_package = [[com.google.protobuf]],
        java_outer_classname = [[WrappersProto]],
        java_multiple_files = true,
        go_package = [[google.golang.org/protobuf/types/known/wrapperspb]],
        cc_enable_arenas = true,
        objc_class_prefix = [[GPB]],
        csharp_namespace = [[Google.Protobuf.WellKnownTypes]],
    },
    syntax = [[proto3]],
}