-- This file is generated by proto-gen-lua. DO NOT EDIT.
local google_protobuf_wrappers_pb = {}

google_protobuf_wrappers_pb.DoubleValue = {
    __call__ = function ()
        local message = {
            value = 0,
        }

        return message
    end,

}

google_protobuf_wrappers_pb.FloatValue = {
    __call__ = function ()
        local message = {
            value = 0,
        }

        return message
    end,

}

google_protobuf_wrappers_pb.Int64Value = {
    __call__ = function ()
        local message = {
            value = 0,
        }

        return message
    end,

}

google_protobuf_wrappers_pb.UInt64Value = {
    __call__ = function ()
        local message = {
            value = 0,
        }

        return message
    end,

}

google_protobuf_wrappers_pb.Int32Value = {
    __call__ = function ()
        local message = {
            value = 0,
        }

        return message
    end,

}

google_protobuf_wrappers_pb.UInt32Value = {
    __call__ = function ()
        local message = {
            value = 0,
        }

        return message
    end,

}

google_protobuf_wrappers_pb.BoolValue = {
    __call__ = function ()
        local message = {
            value = false,
        }

        return message
    end,

}

google_protobuf_wrappers_pb.StringValue = {
    __call__ = function ()
        local message = {
            value = "",
        }

        return message
    end,

}

google_protobuf_wrappers_pb.BytesValue = {
    __call__ = function ()
        local message = {
            value = 0,
        }

        return message
    end,

}

return google_protobuf_wrappers_pb
