-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local comments_comments_pb_desc = require "comments.comments_pb_desc"

local comments_comments_pb = {}

---@alias comments_comments_pb.Enum1
---| 'comments_comments_pb.Enum1.FOO' # = 0
---| 'comments_comments_pb.Enum1.BAR' # = 1

---@class comments_comments_pb.Message1.Message1A : protobuf.Message

---@class comments_comments_pb.Message1.Message1B : protobuf.Message

---@class comments_comments_pb.Message1 : protobuf.Message
---@field Field1A string
---@field Oneof1AField1 string

---@class comments_comments_pb.Message2.Message2A : protobuf.Message

---@class comments_comments_pb.Message2.Message2B : protobuf.Message

---@class comments_comments_pb.Message2 : protobuf.Message

comments_comments_pb.Enum1 = {}
comments_comments_pb.Enum1._FullName = ".goproto.protoc.comments.Enum1"
comments_comments_pb.Enum1._Descriptor = "comments_comments_pb_desc.enum_type[1]"
registry.RegistEnum(".goproto.protoc.comments.Enum1", comments_comments_pb.Enum1)
comments_comments_pb.Enum1.FOO = 0
comments_comments_pb.Enum1.BAR = 1
comments_comments_pb.Enum1[0] = ".goproto.protoc.comments.Enum1.FOO"
comments_comments_pb.Enum1[1] = ".goproto.protoc.comments.Enum1.BAR"

---@type fun():comments_comments_pb.Message1.Message1A
comments_comments_pb.Message1.Message1A = protobuf.Message(comments_comments_pb_desc.message_type[1].nested_type[1])
comments_comments_pb.Message1.Message1A._FullName = ".goproto.protoc.comments.Message1.Message1A"
comments_comments_pb.Message1.Message1A._Descriptor = "comments_comments_pb_desc.message_type[1].nested_type[1]"
registry.RegistMessage(".goproto.protoc.comments.Message1.Message1A", comments_comments_pb.Message1.Message1A)

---@type fun():comments_comments_pb.Message1.Message1B
comments_comments_pb.Message1.Message1B = protobuf.Message(comments_comments_pb_desc.message_type[1].nested_type[2])
comments_comments_pb.Message1.Message1B._FullName = ".goproto.protoc.comments.Message1.Message1B"
comments_comments_pb.Message1.Message1B._Descriptor = "comments_comments_pb_desc.message_type[1].nested_type[2]"
registry.RegistMessage(".goproto.protoc.comments.Message1.Message1B", comments_comments_pb.Message1.Message1B)

---@type fun():comments_comments_pb.Message1
comments_comments_pb.Message1 = protobuf.Message(comments_comments_pb_desc.message_type[1])
comments_comments_pb.Message1._FullName = ".goproto.protoc.comments.Message1"
comments_comments_pb.Message1._Descriptor = "comments_comments_pb_desc.message_type[1]"
registry.RegistMessage(".goproto.protoc.comments.Message1", comments_comments_pb.Message1)

---@type fun():comments_comments_pb.Message2.Message2A
comments_comments_pb.Message2.Message2A = protobuf.Message(comments_comments_pb_desc.message_type[2].nested_type[1])
comments_comments_pb.Message2.Message2A._FullName = ".goproto.protoc.comments.Message2.Message2A"
comments_comments_pb.Message2.Message2A._Descriptor = "comments_comments_pb_desc.message_type[2].nested_type[1]"
registry.RegistMessage(".goproto.protoc.comments.Message2.Message2A", comments_comments_pb.Message2.Message2A)

---@type fun():comments_comments_pb.Message2.Message2B
comments_comments_pb.Message2.Message2B = protobuf.Message(comments_comments_pb_desc.message_type[2].nested_type[2])
comments_comments_pb.Message2.Message2B._FullName = ".goproto.protoc.comments.Message2.Message2B"
comments_comments_pb.Message2.Message2B._Descriptor = "comments_comments_pb_desc.message_type[2].nested_type[2]"
registry.RegistMessage(".goproto.protoc.comments.Message2.Message2B", comments_comments_pb.Message2.Message2B)

---@type fun():comments_comments_pb.Message2
comments_comments_pb.Message2 = protobuf.Message(comments_comments_pb_desc.message_type[2])
comments_comments_pb.Message2._FullName = ".goproto.protoc.comments.Message2"
comments_comments_pb.Message2._Descriptor = "comments_comments_pb_desc.message_type[2]"
registry.RegistMessage(".goproto.protoc.comments.Message2", comments_comments_pb.Message2)


return comments_comments_pb
