-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
return {
    name = [[comments/comments.proto]],
    package = [[goproto.protoc.comments]],
    message_type = {
        {
            name = [[Message1]],
            field = {
                {
                    name = [[Field1A]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_STRING]],
                    json_name = [[Field1A]],
                },
                {
                    name = [[Oneof1AField1]],
                    number = 2,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_STRING]],
                    oneof_index = 0,
                    json_name = [[Oneof1AField1]],
                },
            },
            nested_type = {
                {
                    name = [[Message1A]],
                },
                {
                    name = [[Message1B]],
                },
            },
            extension_range = {
                {
                    start = 100,
                    end_ = 536870912,
                },
            },
            oneof_decl = {
                {
                    name = [[Oneof1a]],
                },
            },
        },
        {
            name = [[Message2]],
            nested_type = {
                {
                    name = [[Message2A]],
                },
                {
                    name = [[Message2B]],
                },
            },
        },
    },
    enum_type = {
        {
            name = [[Enum1]],
            value = {
                {
                    name = [[FOO]],
                    number = 0,
                },
                {
                    name = [[BAR]],
                    number = 1,
                },
            },
        },
    },
    extension = {
        {
            name = [[extension]],
            extendee = [[.goproto.protoc.comments.Message1]],
            number = 100,
            label = [[LABEL_OPTIONAL]],
            type = [[TYPE_MESSAGE]],
            type_name = [[.goproto.protoc.comments.Message1]],
            json_name = [[extension]],
        },
    },
    options = {
        go_package = [[google.golang.org/protobuf/cmd/protoc-gen-go/testdata/comments]],
    },
}