-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local comments_deprecated_pb_desc = require "comments.deprecated_pb_desc"

local comments_deprecated_pb = {}

---@alias comments_deprecated_pb.DeprecatedEnum
---| 'comments_deprecated_pb.DeprecatedEnum.DEPRECATED' # = 0

---@class comments_deprecated_pb.DeprecatedMessage
---@field deprecated_field string

comments_deprecated_pb.DeprecatedEnum = protobuf_reflect.Enum(comments_deprecated_pb_desc.enum_type[1])
comments_deprecated_pb.DeprecatedEnum.DEPRECATED = 0

---@type fun():comments_deprecated_pb.DeprecatedMessage @New a '.goproto.protoc.comments.DeprecatedMessage'
comments_deprecated_pb.DeprecatedMessage = protobuf_reflect.Message(comments_deprecated_pb_desc.message_type[1])


return comments_deprecated_pb
