-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
return {
    name = [[comments/deprecated.proto]],
    package = [[goproto.protoc.comments]],
    message_type = {
        {
            name = [[DeprecatedMessage]],
            field = {
                {
                    name = [[deprecated_field]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_STRING]],
                    options = {
                        deprecated = true,
                    },
                    json_name = [[deprecatedField]],
                },
            },
            options = {
                deprecated = true,
            },
        },
    },
    enum_type = {
        {
            name = [[DeprecatedEnum]],
            value = {
                {
                    name = [[DEPRECATED]],
                    number = 0,
                    options = {
                        deprecated = true,
                    },
                },
            },
            options = {
                deprecated = true,
            },
        },
    },
    options = {
        go_package = [[google.golang.org/protobuf/cmd/protoc-gen-go/testdata/comments]],
        deprecated = true,
    },
    syntax = [[proto3]],
}