-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local comments_deprecated_pb_desc = require "comments.deprecated_pb_desc"

local comments_deprecated_pb = {}

---@alias comments_deprecated_pb.DeprecatedEnum
---| 'comments_deprecated_pb.DeprecatedEnum.DEPRECATED' # = 0

---@class comments_deprecated_pb.DeprecatedMessage : protobuf.Message
---@field deprecated_field string

comments_deprecated_pb.DeprecatedEnum = {}
comments_deprecated_pb.DeprecatedEnum._FullName = ".goproto.protoc.comments.DeprecatedEnum"
comments_deprecated_pb.DeprecatedEnum._Descriptor = "comments_deprecated_pb_desc.enum_type[1]"
comments_deprecated_pb.DeprecatedEnum.DEPRECATED = 0
comments_deprecated_pb.DeprecatedEnum[0] = ".goproto.protoc.comments.DeprecatedEnum.DEPRECATED"
registry.RegistEnum(comments_deprecated_pb.DeprecatedEnum)

---@type fun():comments_deprecated_pb.DeprecatedMessage
comments_deprecated_pb.DeprecatedMessage = protobuf.Message(comments_deprecated_pb_desc.message_type[1])
comments_deprecated_pb.DeprecatedMessage._FullName = ".goproto.protoc.comments.DeprecatedMessage"
comments_deprecated_pb.DeprecatedMessage._Descriptor = "comments_deprecated_pb_desc.message_type[1]"
registry.RegistMessage(comments_deprecated_pb.DeprecatedMessage)


return comments_deprecated_pb
