-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
return {
    name = [[annotations/annotations.proto]],
    package = [[goproto.protoc.annotations]],
    message_type = {
        {
            name = [[AnnotationsTestMessage]],
            field = {
                {
                    name = [[AnnotationsTestField]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_STRING]],
                    json_name = [[AnnotationsTestField]],
                },
            },
        },
    },
    enum_type = {
        {
            name = [[AnnotationsTestEnum]],
            value = {
                {
                    name = [[ANNOTATIONS_TEST_ENUM_VALUE]],
                    number = 0,
                },
            },
        },
    },
    options = {
        go_package = [[google.golang.org/protobuf/cmd/protoc-gen-go/testdata/annotations]],
    },
}