-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local annotations_annotations_pb_desc = require "annotations.annotations_pb_desc"

local annotations_annotations_pb = {}

---@alias annotations_annotations_pb.AnnotationsTestEnum
---| 'annotations_annotations_pb.AnnotationsTestEnum.ANNOTATIONS_TEST_ENUM_VALUE' # = 0

---@class annotations_annotations_pb.AnnotationsTestMessage : protobuf.Message
---@field AnnotationsTestField string

annotations_annotations_pb.AnnotationsTestEnum = {}
annotations_annotations_pb.AnnotationsTestEnum._FullName = ".goproto.protoc.annotations.AnnotationsTestEnum"
annotations_annotations_pb.AnnotationsTestEnum._Descriptor = "annotations_annotations_pb_desc.enum_type[1]"
registry.RegistEnum(".goproto.protoc.annotations.AnnotationsTestEnum", annotations_annotations_pb.AnnotationsTestEnum)
annotations_annotations_pb.AnnotationsTestEnum.ANNOTATIONS_TEST_ENUM_VALUE = 0
annotations_annotations_pb.AnnotationsTestEnum[0] = ".goproto.protoc.annotations.AnnotationsTestEnum.ANNOTATIONS_TEST_ENUM_VALUE"

---@type fun():annotations_annotations_pb.AnnotationsTestMessage
annotations_annotations_pb.AnnotationsTestMessage = protobuf.Message(annotations_annotations_pb_desc.message_type[1])
annotations_annotations_pb.AnnotationsTestMessage._FullName = ".goproto.protoc.annotations.AnnotationsTestMessage"
annotations_annotations_pb.AnnotationsTestMessage._Descriptor = "annotations_annotations_pb_desc.message_type[1]"
registry.RegistMessage(".goproto.protoc.annotations.AnnotationsTestMessage", annotations_annotations_pb.AnnotationsTestMessage)


return annotations_annotations_pb
