-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local annotations_annotations_pb_desc = require "annotations.annotations_pb_desc"

local annotations_annotations_pb = {}

---@alias annotations_annotations_pb.AnnotationsTestEnum
---| 'annotations_annotations_pb.AnnotationsTestEnum.ANNOTATIONS_TEST_ENUM_VALUE' # = 0

---@class annotations_annotations_pb.AnnotationsTestMessage
---@field AnnotationsTestField string

annotations_annotations_pb.AnnotationsTestEnum = protobuf_reflect.Enum(annotations_annotations_pb_desc.enum_type[1])
annotations_annotations_pb.AnnotationsTestEnum.ANNOTATIONS_TEST_ENUM_VALUE = 0

---@type fun():annotations_annotations_pb.AnnotationsTestMessage @New a '.goproto.protoc.annotations.AnnotationsTestMessage'
annotations_annotations_pb.AnnotationsTestMessage = protobuf_reflect.Message(annotations_annotations_pb_desc.message_type[1])


return annotations_annotations_pb
