-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"

local import_public_sub_b_pb = require "import_public.sub.b_pb"
local import_public_sub2_a_pb = require "import_public.sub2.a_pb"

local import_public_sub_a_pb_desc = require "import_public.sub.a_pb_desc"

local import_public_sub_a_pb = {}

---@alias import_public_sub_a_pb.E
---| 'import_public_sub_a_pb.E.ZERO' # = 0

---@alias import_public_sub_a_pb.M.Subenum
---| 'import_public_sub_a_pb.M.Subenum.M_ZERO' # = 0

---@alias import_public_sub_a_pb.M.Submessage.Submessage_Subenum
---| 'import_public_sub_a_pb.M.Submessage.Submessage_Subenum.M_SUBMESSAGE_ZERO' # = 0

---@class import_public_sub_a_pb.M.Submessage
---@field submessage_oneof_int32 number
---@field submessage_oneof_int64 number

---@class import_public_sub_a_pb.M
---@field m2 import_public_sub_b_pb.M2
---@field s string
---@field b string
---@field f number
---@field oneof_int32 number
---@field oneof_int64 number

import_public_sub_a_pb.E = protobuf_reflect.Enum(import_public_sub_a_pb_desc.enum_type[1])
import_public_sub_a_pb.E.ZERO = 0

import_public_sub_a_pb.M.Subenum = protobuf_reflect.Enum(import_public_sub_a_pb_desc.message_type[1].enum_type[1])
import_public_sub_a_pb.M.Subenum.M_ZERO = 0

import_public_sub_a_pb.M.Submessage.Submessage_Subenum = protobuf_reflect.Enum(import_public_sub_a_pb_desc.message_type[1].nested_type[1].enum_type[1])
import_public_sub_a_pb.M.Submessage.Submessage_Subenum.M_SUBMESSAGE_ZERO = 0

---@type fun():import_public_sub_a_pb.M.Submessage @New a '.goproto.protoc.import_public.sub.M.Submessage'
import_public_sub_a_pb.M.Submessage = protobuf_reflect.Message(import_public_sub_a_pb_desc.message_type[1].nested_type[1])

---@type fun():import_public_sub_a_pb.M @New a '.goproto.protoc.import_public.sub.M'
import_public_sub_a_pb.M = protobuf_reflect.Message(import_public_sub_a_pb_desc.message_type[1])


return import_public_sub_a_pb
