-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

return {
    name = [[import_public/sub/a.proto]],
    package = [[goproto.protoc.import_public.sub]],
    dependency = {
        [[import_public/sub/b.proto]],
        [[import_public/sub2/a.proto]],
    },
    message_type = {
        {
            name = [[M]],
            field = {
                {
                    name = [[m2]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_MESSAGE]],
                    type_name = [[.goproto.protoc.import_public.sub.M2]],
                    json_name = [[m2]],
                },
                {
                    name = [[s]],
                    number = 4,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_STRING]],
                    default_value = [[default]],
                    json_name = [[s]],
                },
                {
                    name = [[b]],
                    number = 5,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_BYTES]],
                    default_value = [[default]],
                    json_name = [[b]],
                },
                {
                    name = [[f]],
                    number = 6,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_DOUBLE]],
                    default_value = [[nan]],
                    json_name = [[f]],
                },
                {
                    name = [[oneof_int32]],
                    number = 2,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_INT32]],
                    oneof_index = 0,
                    json_name = [[oneofInt32]],
                },
                {
                    name = [[oneof_int64]],
                    number = 3,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_INT64]],
                    oneof_index = 0,
                    json_name = [[oneofInt64]],
                },
            },
            nested_type = {
                {
                    name = [[Submessage]],
                    field = {
                        {
                            name = [[submessage_oneof_int32]],
                            number = 1,
                            label = [[LABEL_OPTIONAL]],
                            type = [[TYPE_INT32]],
                            oneof_index = 0,
                            json_name = [[submessageOneofInt32]],
                        },
                        {
                            name = [[submessage_oneof_int64]],
                            number = 2,
                            label = [[LABEL_OPTIONAL]],
                            type = [[TYPE_INT64]],
                            oneof_index = 0,
                            json_name = [[submessageOneofInt64]],
                        },
                    },
                    enum_type = {
                        {
                            name = [[Submessage_Subenum]],
                            value = {
                                {
                                    name = [[M_SUBMESSAGE_ZERO]],
                                    number = 0,
                                },
                            },
                        },
                    },
                    oneof_decl = {
                        {
                            name = [[submessage_oneof_field]],
                        },
                    },
                },
            },
            enum_type = {
                {
                    name = [[Subenum]],
                    value = {
                        {
                            name = [[M_ZERO]],
                            number = 0,
                        },
                    },
                },
            },
            extension_range = {
                {
                    start = 100,
                    end_ = 536870912,
                },
            },
            oneof_decl = {
                {
                    name = [[oneof_field]],
                },
            },
        },
    },
    enum_type = {
        {
            name = [[E]],
            value = {
                {
                    name = [[ZERO]],
                    number = 0,
                },
            },
        },
    },
    extension = {
        {
            name = [[extension_field]],
            extendee = [[.goproto.protoc.import_public.sub.M]],
            number = 100,
            label = [[LABEL_OPTIONAL]],
            type = [[TYPE_STRING]],
            json_name = [[extensionField]],
        },
    },
    options = {
        go_package = [[google.golang.org/protobuf/cmd/protoc-gen-go/testdata/import_public/sub]],
    },
    public_dependency = {
        1,
    },
}