-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local import_public_sub_b_pb_desc = require "import_public.sub.b_pb_desc"

local import_public_sub_b_pb = {}

---@class import_public_sub_b_pb.M2

---@type fun():import_public_sub_b_pb.M2 @New a '.goproto.protoc.import_public.sub.M2'
import_public_sub_b_pb.M2 = protobuf_reflect.Message(import_public_sub_b_pb_desc.message_type[1])


return import_public_sub_b_pb
