-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local import_public_sub_b_pb_desc = require "import_public.sub.b_pb_desc"

local import_public_sub_b_pb = {}

---@class import_public_sub_b_pb.M2 : protobuf.Message

---@type fun():import_public_sub_b_pb.M2
import_public_sub_b_pb.M2 = protobuf.Message(import_public_sub_b_pb_desc.message_type[1])
import_public_sub_b_pb.M2._FullName = ".goproto.protoc.import_public.sub.M2"
import_public_sub_b_pb.M2._Descriptor = "import_public_sub_b_pb_desc.message_type[1]"
registry.RegistMessage(import_public_sub_b_pb.M2)


return import_public_sub_b_pb
