-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"

local google_protobuf_descriptor_pb = require "google.protobuf.descriptor_pb"

local extensions_proto3_ext3_pb_desc = require "extensions.proto3.ext3_pb_desc"

local extensions_proto3_ext3_pb = {}

---@alias extensions_proto3_ext3_pb.Enum
---| 'extensions_proto3_ext3_pb.Enum.ZERO' # = 0

---@class extensions_proto3_ext3_pb.Message : protobuf.Message

extensions_proto3_ext3_pb.Enum = {}
extensions_proto3_ext3_pb.Enum._FullName = ".goproto.protoc.extension.proto3.Enum"
extensions_proto3_ext3_pb.Enum._Descriptor = "extensions_proto3_ext3_pb_desc.enum_type[1]"
extensions_proto3_ext3_pb.Enum.ZERO = 0
extensions_proto3_ext3_pb.Enum[0] = ".goproto.protoc.extension.proto3.Enum.ZERO"
registry.RegistEnum(extensions_proto3_ext3_pb.Enum)

---@type fun():extensions_proto3_ext3_pb.Message
extensions_proto3_ext3_pb.Message = protobuf.Message(extensions_proto3_ext3_pb_desc.message_type[1])
extensions_proto3_ext3_pb.Message._FullName = ".goproto.protoc.extension.proto3.Message"
extensions_proto3_ext3_pb.Message._Descriptor = "extensions_proto3_ext3_pb_desc.message_type[1]"
registry.RegistMessage(extensions_proto3_ext3_pb.Message)


return extensions_proto3_ext3_pb
