-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"

local imports_test_a_1_m2_pb = require "imports.test_a_1.m2_pb"

local imports_test_import_a1m2_pb_desc = require "imports.test_import_a1m2_pb_desc"

local imports_test_import_a1m2_pb = {}

---@class imports_test_import_a1m2_pb.A1M2 : protobuf.Message
---@field f imports_test_a_1_m2_pb.M2

---@type fun():imports_test_import_a1m2_pb.A1M2
imports_test_import_a1m2_pb.A1M2 = protobuf.Message(imports_test_import_a1m2_pb_desc.message_type[1])
imports_test_import_a1m2_pb.A1M2._FullName = ".test.A1M2"
imports_test_import_a1m2_pb.A1M2._Descriptor = "imports_test_import_a1m2_pb_desc.message_type[1]"
registry.RegistMessage(imports_test_import_a1m2_pb.A1M2)


return imports_test_import_a1m2_pb
