-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"

local imports_test_a_1_m1_pb = require "imports.test_a_1.m1_pb"
local imports_test_a_1_m2_pb = require "imports.test_a_1.m2_pb"
local imports_test_a_2_m3_pb = require "imports.test_a_2.m3_pb"
local imports_test_a_2_m4_pb = require "imports.test_a_2.m4_pb"
local imports_test_b_1_m1_pb = require "imports.test_b_1.m1_pb"
local imports_test_b_1_m2_pb = require "imports.test_b_1.m2_pb"
local imports_fmt_m_pb = require "imports.fmt.m_pb"

local imports_test_import_all_pb_desc = require "imports.test_import_all_pb_desc"

local imports_test_import_all_pb = {}

---@class imports_test_import_all_pb.All : protobuf.Message
---@field am1 imports_test_a_1_m1_pb.M1
---@field am2 imports_test_a_1_m2_pb.M2
---@field bm1 imports_test_b_1_m1_pb.M1
---@field bm2 imports_test_b_1_m2_pb.M2
---@field fmt imports_fmt_m_pb.M

---@type fun():imports_test_import_all_pb.All
imports_test_import_all_pb.All = protobuf.Message(imports_test_import_all_pb_desc.message_type[1])
imports_test_import_all_pb.All._FullName = ".test.All"
imports_test_import_all_pb.All._Descriptor = "imports_test_import_all_pb_desc.message_type[1]"
registry.RegistMessage(imports_test_import_all_pb.All)


return imports_test_import_all_pb
