-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
return {
    name = [[imports/fmt/m.proto]],
    package = [[fmt]],
    message_type = {
        {
            name = [[M]],
        },
    },
    options = {
        go_package = [[google.golang.org/protobuf/cmd/protoc-gen-go/testdata/imports/fmt]],
    },
    syntax = [[proto3]],
}