-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local imports_fmt_m_pb_desc = require "imports.fmt.m_pb_desc"

local imports_fmt_m_pb = {}

---@class imports_fmt_m_pb.M

---@type fun():imports_fmt_m_pb.M @New a '.fmt.M'
imports_fmt_m_pb.M = protobuf_reflect.Message(imports_fmt_m_pb_desc.message_type[1])


return imports_fmt_m_pb
