-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local imports_fmt_m_pb_desc = require "imports.fmt.m_pb_desc"

local imports_fmt_m_pb = {}

---@class imports_fmt_m_pb.M : protobuf.Message

---@type fun():imports_fmt_m_pb.M
imports_fmt_m_pb.M = protobuf.Message(imports_fmt_m_pb_desc.message_type[1])
imports_fmt_m_pb.M._FullName = ".fmt.M"
imports_fmt_m_pb.M._Descriptor = "imports_fmt_m_pb_desc.message_type[1]"
registry.RegistMessage(".fmt.M", imports_fmt_m_pb.M)


return imports_fmt_m_pb
