-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local issue780_oneof_conflict_test_pb_desc = require "issue780_oneof_conflict.test_pb_desc"

local issue780_oneof_conflict_test_pb = {}

---@class issue780_oneof_conflict_test_pb.Foo
---@field get_bar string

---@type fun():issue780_oneof_conflict_test_pb.Foo @New a '.oneoftest.Foo'
issue780_oneof_conflict_test_pb.Foo = protobuf_reflect.Message(issue780_oneof_conflict_test_pb_desc.message_type[1])


return issue780_oneof_conflict_test_pb
