-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local issue780_oneof_conflict_test_pb_desc = require "issue780_oneof_conflict.test_pb_desc"

local issue780_oneof_conflict_test_pb = {}

---@class issue780_oneof_conflict_test_pb.Foo : protobuf.Message
---@field get_bar string

---@type fun():issue780_oneof_conflict_test_pb.Foo
issue780_oneof_conflict_test_pb.Foo = protobuf.Message(issue780_oneof_conflict_test_pb_desc.message_type[1])
issue780_oneof_conflict_test_pb.Foo._FullName = ".oneoftest.Foo"
issue780_oneof_conflict_test_pb.Foo._Descriptor = "issue780_oneof_conflict_test_pb_desc.message_type[1]"
registry.RegistMessage(issue780_oneof_conflict_test_pb.Foo)


return issue780_oneof_conflict_test_pb
