-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
return {
    name = [[issue780_oneof_conflict/test.proto]],
    package = [[oneoftest]],
    message_type = {
        {
            name = [[Foo]],
            field = {
                {
                    name = [[get_bar]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_STRING]],
                    oneof_index = 0,
                    json_name = [[getBar]],
                },
            },
            oneof_decl = {
                {
                    name = [[bar]],
                },
            },
        },
    },
    options = {
        go_package = [[google.golang.org/protobuf/cmd/protoc-gen-go/testdata/issue780_oneof_conflict]],
    },
}