-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local import_public_sub2_a_pb_desc = require "import_public.sub2.a_pb_desc"

local import_public_sub2_a_pb = {}

---@class import_public_sub2_a_pb.Sub2Message : protobuf.Message

---@type fun():import_public_sub2_a_pb.Sub2Message
import_public_sub2_a_pb.Sub2Message = protobuf.Message(import_public_sub2_a_pb_desc.message_type[1])
import_public_sub2_a_pb.Sub2Message._FullName = ".goproto.protoc.import_public.sub2.Sub2Message"
import_public_sub2_a_pb.Sub2Message._Descriptor = "import_public_sub2_a_pb_desc.message_type[1]"
registry.RegistMessage(".goproto.protoc.import_public.sub2.Sub2Message", import_public_sub2_a_pb.Sub2Message)


return import_public_sub2_a_pb
