-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local import_public_sub2_a_pb_desc = require "import_public.sub2.a_pb_desc"

local import_public_sub2_a_pb = {}

---@class import_public_sub2_a_pb.Sub2Message

---@type fun():import_public_sub2_a_pb.Sub2Message @New a '.goproto.protoc.import_public.sub2.Sub2Message'
import_public_sub2_a_pb.Sub2Message = protobuf_reflect.Message(import_public_sub2_a_pb_desc.message_type[1])


return import_public_sub2_a_pb
