-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
return {
    name = [[import_public/sub2/a.proto]],
    package = [[goproto.protoc.import_public.sub2]],
    message_type = {
        {
            name = [[Sub2Message]],
        },
    },
    options = {
        go_package = [[google.golang.org/protobuf/cmd/protoc-gen-go/testdata/import_public/sub2]],
    },
}