-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local imports_test_b_1_m1_pb_desc = require "imports.test_b_1.m1_pb_desc"

local imports_test_b_1_m1_pb = {}

---@class imports_test_b_1_m1_pb.M1

---@type fun():imports_test_b_1_m1_pb.M1 @New a '.test.b.part1.M1'
imports_test_b_1_m1_pb.M1 = protobuf_reflect.Message(imports_test_b_1_m1_pb_desc.message_type[1])


return imports_test_b_1_m1_pb
