-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

return {
    name = [[imports/test_b_1/m2.proto]],
    package = [[test.b.part2]],
    message_type = {
        {
            name = [[M2]],
        },
    },
    options = {
        go_package = [[google.golang.org/protobuf/cmd/protoc-gen-go/testdata/imports/test_b_1;beta]],
    },
    syntax = [[proto3]],
}