-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local imports_test_b_1_m2_pb_desc = require "imports.test_b_1.m2_pb_desc"

local imports_test_b_1_m2_pb = {}

---@class imports_test_b_1_m2_pb.M2 : protobuf.Message

---@type fun():imports_test_b_1_m2_pb.M2
imports_test_b_1_m2_pb.M2 = protobuf.Message(imports_test_b_1_m2_pb_desc.message_type[1])
imports_test_b_1_m2_pb.M2._FullName = ".test.b.part2.M2"
imports_test_b_1_m2_pb.M2._Descriptor = "imports_test_b_1_m2_pb_desc.message_type[1]"
registry.RegistMessage(".test.b.part2.M2", imports_test_b_1_m2_pb.M2)


return imports_test_b_1_m2_pb
