-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local nopackage_nopackage_pb_desc = require "nopackage.nopackage_pb_desc"

local nopackage_nopackage_pb = {}

---@alias nopackage_nopackage_pb.Enum
---| 'nopackage_nopackage_pb.Enum.ZERO' # = 0

---@class nopackage_nopackage_pb.Message
---@field string_field string
---@field enum_field nopackage_nopackage_pb.Enum

nopackage_nopackage_pb.Enum = protobuf_reflect.Enum(nopackage_nopackage_pb_desc.enum_type[1])
nopackage_nopackage_pb.Enum.ZERO = 0

---@type fun():nopackage_nopackage_pb.Message @New a '.Message'
nopackage_nopackage_pb.Message = protobuf_reflect.Message(nopackage_nopackage_pb_desc.message_type[1])


return nopackage_nopackage_pb
