-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"


local nopackage_nopackage_pb_desc = require "nopackage.nopackage_pb_desc"

local nopackage_nopackage_pb = {}

---@alias nopackage_nopackage_pb.Enum
---| 'nopackage_nopackage_pb.Enum.ZERO' # = 0

---@class nopackage_nopackage_pb.Message : protobuf.Message
---@field string_field string
---@field enum_field nopackage_nopackage_pb.Enum

nopackage_nopackage_pb.Enum = {}
nopackage_nopackage_pb.Enum._FullName = ".Enum"
nopackage_nopackage_pb.Enum._Descriptor = "nopackage_nopackage_pb_desc.enum_type[1]"
registry.RegistEnum(".Enum", nopackage_nopackage_pb.Enum)
nopackage_nopackage_pb.Enum.ZERO = 0
nopackage_nopackage_pb.Enum[0] = ".Enum.ZERO"

---@type fun():nopackage_nopackage_pb.Message
nopackage_nopackage_pb.Message = protobuf.Message(nopackage_nopackage_pb_desc.message_type[1])
nopackage_nopackage_pb.Message._FullName = ".Message"
nopackage_nopackage_pb.Message._Descriptor = "nopackage_nopackage_pb_desc.message_type[1]"
registry.RegistMessage(".Message", nopackage_nopackage_pb.Message)


return nopackage_nopackage_pb
