-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"

local extensions_base_base_pb = require "extensions.base.base_pb"
local extensions_extra_extra_pb = require "extensions.extra.extra_pb"

local extensions_ext_ext_pb_desc = require "extensions.ext.ext_pb_desc"

local extensions_ext_ext_pb = {}

---@alias extensions_ext_ext_pb.Enum
---| 'extensions_ext_ext_pb.Enum.ZERO' # = 0

---@class extensions_ext_ext_pb.Message.M : protobuf.Message

---@class extensions_ext_ext_pb.Message : protobuf.Message
---@field data string

---@class extensions_ext_ext_pb.ExtensionGroup : protobuf.Message
---@field extension_group string

---@class extensions_ext_ext_pb.ExtendingMessage.ExtendingMessageSubmessage : protobuf.Message

---@class extensions_ext_ext_pb.ExtendingMessage : protobuf.Message

---@class extensions_ext_ext_pb.RepeatedGroup : protobuf.Message
---@field repeated_x_group string[]

---@class extensions_ext_ext_pb.Extendable : protobuf.Message

---@class extensions_ext_ext_pb.MessageSetWireFormatExtension : protobuf.Message

extensions_ext_ext_pb.Enum = {}
extensions_ext_ext_pb.Enum._FullName = ".goproto.protoc.extension.ext.Enum"
extensions_ext_ext_pb.Enum._Descriptor = "extensions_ext_ext_pb_desc.enum_type[1]"
extensions_ext_ext_pb.Enum.ZERO = 0
extensions_ext_ext_pb.Enum[0] = ".goproto.protoc.extension.ext.Enum.ZERO"
registry.RegistEnum(extensions_ext_ext_pb.Enum)

---@type fun():extensions_ext_ext_pb.Message.M
extensions_ext_ext_pb.Message.M = protobuf.Message(extensions_ext_ext_pb_desc.message_type[1].nested_type[1])
extensions_ext_ext_pb.Message.M._FullName = ".goproto.protoc.extension.ext.Message.M"
extensions_ext_ext_pb.Message.M._Descriptor = "extensions_ext_ext_pb_desc.message_type[1].nested_type[1]"
registry.RegistMessage(extensions_ext_ext_pb.Message.M)

---@type fun():extensions_ext_ext_pb.Message
extensions_ext_ext_pb.Message = protobuf.Message(extensions_ext_ext_pb_desc.message_type[1])
extensions_ext_ext_pb.Message._FullName = ".goproto.protoc.extension.ext.Message"
extensions_ext_ext_pb.Message._Descriptor = "extensions_ext_ext_pb_desc.message_type[1]"
registry.RegistMessage(extensions_ext_ext_pb.Message)

---@type fun():extensions_ext_ext_pb.ExtensionGroup
extensions_ext_ext_pb.ExtensionGroup = protobuf.Message(extensions_ext_ext_pb_desc.message_type[2])
extensions_ext_ext_pb.ExtensionGroup._FullName = ".goproto.protoc.extension.ext.ExtensionGroup"
extensions_ext_ext_pb.ExtensionGroup._Descriptor = "extensions_ext_ext_pb_desc.message_type[2]"
registry.RegistMessage(extensions_ext_ext_pb.ExtensionGroup)

---@type fun():extensions_ext_ext_pb.ExtendingMessage.ExtendingMessageSubmessage
extensions_ext_ext_pb.ExtendingMessage.ExtendingMessageSubmessage = protobuf.Message(extensions_ext_ext_pb_desc.message_type[3].nested_type[1])
extensions_ext_ext_pb.ExtendingMessage.ExtendingMessageSubmessage._FullName = ".goproto.protoc.extension.ext.ExtendingMessage.ExtendingMessageSubmessage"
extensions_ext_ext_pb.ExtendingMessage.ExtendingMessageSubmessage._Descriptor = "extensions_ext_ext_pb_desc.message_type[3].nested_type[1]"
registry.RegistMessage(extensions_ext_ext_pb.ExtendingMessage.ExtendingMessageSubmessage)

---@type fun():extensions_ext_ext_pb.ExtendingMessage
extensions_ext_ext_pb.ExtendingMessage = protobuf.Message(extensions_ext_ext_pb_desc.message_type[3])
extensions_ext_ext_pb.ExtendingMessage._FullName = ".goproto.protoc.extension.ext.ExtendingMessage"
extensions_ext_ext_pb.ExtendingMessage._Descriptor = "extensions_ext_ext_pb_desc.message_type[3]"
registry.RegistMessage(extensions_ext_ext_pb.ExtendingMessage)

---@type fun():extensions_ext_ext_pb.RepeatedGroup
extensions_ext_ext_pb.RepeatedGroup = protobuf.Message(extensions_ext_ext_pb_desc.message_type[4])
extensions_ext_ext_pb.RepeatedGroup._FullName = ".goproto.protoc.extension.ext.RepeatedGroup"
extensions_ext_ext_pb.RepeatedGroup._Descriptor = "extensions_ext_ext_pb_desc.message_type[4]"
registry.RegistMessage(extensions_ext_ext_pb.RepeatedGroup)

---@type fun():extensions_ext_ext_pb.Extendable
extensions_ext_ext_pb.Extendable = protobuf.Message(extensions_ext_ext_pb_desc.message_type[5])
extensions_ext_ext_pb.Extendable._FullName = ".goproto.protoc.extension.ext.Extendable"
extensions_ext_ext_pb.Extendable._Descriptor = "extensions_ext_ext_pb_desc.message_type[5]"
registry.RegistMessage(extensions_ext_ext_pb.Extendable)

---@type fun():extensions_ext_ext_pb.MessageSetWireFormatExtension
extensions_ext_ext_pb.MessageSetWireFormatExtension = protobuf.Message(extensions_ext_ext_pb_desc.message_type[6])
extensions_ext_ext_pb.MessageSetWireFormatExtension._FullName = ".goproto.protoc.extension.ext.MessageSetWireFormatExtension"
extensions_ext_ext_pb.MessageSetWireFormatExtension._Descriptor = "extensions_ext_ext_pb_desc.message_type[6]"
registry.RegistMessage(extensions_ext_ext_pb.MessageSetWireFormatExtension)


return extensions_ext_ext_pb
