-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"

local extensions_base_base_pb = require "extensions.base.base_pb"
local extensions_extra_extra_pb = require "extensions.extra.extra_pb"

local extensions_ext_ext_pb_desc = require "extensions.ext.ext_pb_desc"

local extensions_ext_ext_pb = {}

---@alias extensions_ext_ext_pb.Enum
---| 'extensions_ext_ext_pb.Enum.ZERO' # = 0

---@class extensions_ext_ext_pb.Message.M

---@class extensions_ext_ext_pb.Message
---@field data string

---@class extensions_ext_ext_pb.ExtensionGroup
---@field extension_group string

---@class extensions_ext_ext_pb.ExtendingMessage.ExtendingMessageSubmessage

---@class extensions_ext_ext_pb.ExtendingMessage

---@class extensions_ext_ext_pb.RepeatedGroup
---@field repeated_x_group string[]

---@class extensions_ext_ext_pb.Extendable

---@class extensions_ext_ext_pb.MessageSetWireFormatExtension

extensions_ext_ext_pb.Enum = protobuf_reflect.Enum(extensions_ext_ext_pb_desc.enum_type[1])
extensions_ext_ext_pb.Enum.ZERO = 0

---@type fun():extensions_ext_ext_pb.Message.M @New a '.goproto.protoc.extension.ext.Message.M'
extensions_ext_ext_pb.Message.M = protobuf_reflect.Message(extensions_ext_ext_pb_desc.message_type[1].nested_type[1])

---@type fun():extensions_ext_ext_pb.Message @New a '.goproto.protoc.extension.ext.Message'
extensions_ext_ext_pb.Message = protobuf_reflect.Message(extensions_ext_ext_pb_desc.message_type[1])

---@type fun():extensions_ext_ext_pb.ExtensionGroup @New a '.goproto.protoc.extension.ext.ExtensionGroup'
extensions_ext_ext_pb.ExtensionGroup = protobuf_reflect.Message(extensions_ext_ext_pb_desc.message_type[2])

---@type fun():extensions_ext_ext_pb.ExtendingMessage.ExtendingMessageSubmessage @New a '.goproto.protoc.extension.ext.ExtendingMessage.ExtendingMessageSubmessage'
extensions_ext_ext_pb.ExtendingMessage.ExtendingMessageSubmessage = protobuf_reflect.Message(extensions_ext_ext_pb_desc.message_type[3].nested_type[1])

---@type fun():extensions_ext_ext_pb.ExtendingMessage @New a '.goproto.protoc.extension.ext.ExtendingMessage'
extensions_ext_ext_pb.ExtendingMessage = protobuf_reflect.Message(extensions_ext_ext_pb_desc.message_type[3])

---@type fun():extensions_ext_ext_pb.RepeatedGroup @New a '.goproto.protoc.extension.ext.RepeatedGroup'
extensions_ext_ext_pb.RepeatedGroup = protobuf_reflect.Message(extensions_ext_ext_pb_desc.message_type[4])

---@type fun():extensions_ext_ext_pb.Extendable @New a '.goproto.protoc.extension.ext.Extendable'
extensions_ext_ext_pb.Extendable = protobuf_reflect.Message(extensions_ext_ext_pb_desc.message_type[5])

---@type fun():extensions_ext_ext_pb.MessageSetWireFormatExtension @New a '.goproto.protoc.extension.ext.MessageSetWireFormatExtension'
extensions_ext_ext_pb.MessageSetWireFormatExtension = protobuf_reflect.Message(extensions_ext_ext_pb_desc.message_type[6])


return extensions_ext_ext_pb
