-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"

local google_protobuf_descriptor_pb = require "google.protobuf.descriptor_pb"

local google_protobuf_compiler_plugin_pb_desc = require "google.protobuf.compiler.plugin_pb_desc"

local google_protobuf_compiler_plugin_pb = {}

---@class google_protobuf_compiler_plugin_pb.Version
---@field major number
---@field minor number
---@field patch number
---@field suffix string

---@class google_protobuf_compiler_plugin_pb.CodeGeneratorRequest
---@field file_to_generate string[]
---@field parameter string
---@field proto_file google_protobuf_descriptor_pb.FileDescriptorProto[]
---@field compiler_version google_protobuf_compiler_plugin_pb.Version

---@alias google_protobuf_compiler_plugin_pb.CodeGeneratorResponse.Feature
---| 'google_protobuf_compiler_plugin_pb.CodeGeneratorResponse.Feature.FEATURE_NONE' # = 0
---| 'google_protobuf_compiler_plugin_pb.CodeGeneratorResponse.Feature.FEATURE_PROTO3_OPTIONAL' # = 1

---@class google_protobuf_compiler_plugin_pb.CodeGeneratorResponse.File
---@field name string
---@field insertion_point string
---@field content string
---@field generated_code_info google_protobuf_descriptor_pb.GeneratedCodeInfo

---@class google_protobuf_compiler_plugin_pb.CodeGeneratorResponse
---@field error string
---@field supported_features number
---@field file google_protobuf_compiler_plugin_pb.CodeGeneratorResponse.File[]

---@type fun():google_protobuf_compiler_plugin_pb.Version @New a '.google.protobuf.compiler.Version'
google_protobuf_compiler_plugin_pb.Version = protobuf_reflect.Message(google_protobuf_compiler_plugin_pb_desc.message_type[1])

---@type fun():google_protobuf_compiler_plugin_pb.CodeGeneratorRequest @New a '.google.protobuf.compiler.CodeGeneratorRequest'
google_protobuf_compiler_plugin_pb.CodeGeneratorRequest = protobuf_reflect.Message(google_protobuf_compiler_plugin_pb_desc.message_type[2])

google_protobuf_compiler_plugin_pb.CodeGeneratorResponse.Feature = protobuf_reflect.Enum(google_protobuf_compiler_plugin_pb_desc.message_type[3].enum_type[1])
google_protobuf_compiler_plugin_pb.CodeGeneratorResponse.Feature.FEATURE_NONE = 0
google_protobuf_compiler_plugin_pb.CodeGeneratorResponse.Feature.FEATURE_PROTO3_OPTIONAL = 1

---@type fun():google_protobuf_compiler_plugin_pb.CodeGeneratorResponse.File @New a '.google.protobuf.compiler.CodeGeneratorResponse.File'
google_protobuf_compiler_plugin_pb.CodeGeneratorResponse.File = protobuf_reflect.Message(google_protobuf_compiler_plugin_pb_desc.message_type[3].nested_type[1])

---@type fun():google_protobuf_compiler_plugin_pb.CodeGeneratorResponse @New a '.google.protobuf.compiler.CodeGeneratorResponse'
google_protobuf_compiler_plugin_pb.CodeGeneratorResponse = protobuf_reflect.Message(google_protobuf_compiler_plugin_pb_desc.message_type[3])


return google_protobuf_compiler_plugin_pb
