-- This file is generated by proto-gen-lua. DO NOT EDIT.
local google_protobuf_descriptor_pb = require "google.protobuf.descriptor_pb"
local google_protobuf_compiler_plugin_pb = {}

google_protobuf_compiler_plugin_pb.Version = {
    __call__ = function ()
        local message = {
            major = 0,
            minor = 0,
            patch = 0,
            suffix = "",
        }

        return message
    end
,
}

google_protobuf_compiler_plugin_pb.CodeGeneratorRequest = {
    __call__ = function ()
        local message = {
            file_to_generate = {},
            parameter = "",
            proto_file = {},
            compiler_version = google_protobuf_compiler_plugin_pb.Version(),
        }

        return message
    end
,
}

google_protobuf_compiler_plugin_pb.CodeGeneratorResponse = {
    Feature = {
        FEATURE_NONE = 0,
        FEATURE_PROTO3_OPTIONAL = 1,
    }
,
    File = {
        __call__ = function ()
            local message = {
                name = "",
                insertion_point = "",
                content = "",
                generated_code_info = google_protobuf_descriptor_pb.GeneratedCodeInfo(),
            }

            return message
        end
,
    }
,
    __call__ = function ()
        local message = {
            error = "",
            supported_features = 0,
            file = {},
        }

        return message
    end
,
}

return google_protobuf_compiler_plugin_pb
