-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"

local import_public_sub_a_pb = require "import_public.sub.a_pb"

local import_public_b_pb_desc = require "import_public.b_pb_desc"

local import_public_b_pb = {}

---@class import_public_b_pb.Local : protobuf.Message
---@field m import_public_sub_a_pb.M
---@field e import_public_sub_a_pb.E

---@type fun():import_public_b_pb.Local
import_public_b_pb.Local = protobuf.Message(import_public_b_pb_desc.message_type[1])
import_public_b_pb.Local._FullName = ".goproto.protoc.import_public.Local"
import_public_b_pb.Local._Descriptor = "import_public_b_pb_desc.message_type[1]"
registry.RegistMessage(import_public_b_pb.Local)


return import_public_b_pb
