-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

return {
    name = [[import_public/b.proto]],
    package = [[goproto.protoc.import_public]],
    dependency = {
        [[import_public/sub/a.proto]],
    },
    message_type = {
        {
            name = [[Local]],
            field = {
                {
                    name = [[m]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_MESSAGE]],
                    type_name = [[.goproto.protoc.import_public.sub.M]],
                    json_name = [[m]],
                },
                {
                    name = [[e]],
                    number = 2,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_ENUM]],
                    type_name = [[.goproto.protoc.import_public.sub.E]],
                    json_name = [[e]],
                },
            },
        },
    },
    options = {
        go_package = [[google.golang.org/protobuf/cmd/protoc-gen-go/testdata/import_public]],
    },
}