-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.2'
-- The proto-gen-lua version is 'Develop'

local protobuf = require "protobuf.protobuf"
local registry = require "protobuf.registry"

local import_public_a_pb = require "import_public.a_pb"

local import_public_c_pb_desc = require "import_public.c_pb_desc"

local import_public_c_pb = {}

---@class import_public_c_pb.UsingPublicImport : protobuf.Message
---@field local import_public_b_pb.Local
---@field sub2 import_public_sub2_a_pb.Sub2Message

---@type fun():import_public_c_pb.UsingPublicImport
import_public_c_pb.UsingPublicImport = protobuf.Message(import_public_c_pb_desc.message_type[1])
import_public_c_pb.UsingPublicImport._FullName = ".goproto.protoc.import_public.UsingPublicImport"
import_public_c_pb.UsingPublicImport._Descriptor = "import_public_c_pb_desc.message_type[1]"
registry.RegistMessage(import_public_c_pb.UsingPublicImport)


return import_public_c_pb
