-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
return {
    name = [[import_public/c.proto]],
    package = [[goproto.protoc.import_public]],
    dependency = {
        [[import_public/a.proto]],
    },
    message_type = {
        {
            name = [[UsingPublicImport]],
            field = {
                {
                    name = [[local]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_MESSAGE]],
                    type_name = [[.goproto.protoc.import_public.Local]],
                    json_name = [[local]],
                },
                {
                    name = [[sub2]],
                    number = 2,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_MESSAGE]],
                    type_name = [[.goproto.protoc.import_public.sub2.Sub2Message]],
                    json_name = [[sub2]],
                },
            },
        },
    },
    options = {
        go_package = [[google.golang.org/protobuf/cmd/protoc-gen-go/testdata/import_public]],
    },
}