-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
return {
    name = [[extensions/base/base.proto]],
    package = [[goproto.protoc.extension.base]],
    message_type = {
        {
            name = [[BaseMessage]],
            field = {
                {
                    name = [[field]],
                    number = 1,
                    label = [[LABEL_OPTIONAL]],
                    type = [[TYPE_STRING]],
                    json_name = [[field]],
                },
            },
            extension_range = {
                {
                    start = 4,
                    end_ = 10,
                },
                {
                    start = 16,
                    end_ = 536870912,
                },
            },
        },
        {
            name = [[MessageSetWireFormatMessage]],
            extension_range = {
                {
                    start = 100,
                    end_ = 536870912,
                },
            },
        },
    },
    options = {
        go_package = [[google.golang.org/protobuf/cmd/protoc-gen-go/testdata/extensions/base]],
    },
}