-- This file is generated by proto-gen-lua. DO NOT EDIT.
-- The protoc version is 'v3.19.1'
-- The proto-gen-lua version is 'Develop'
local protobuf_reflect = require "protobuf.reflect"


local extensions_base_base_pb_desc = require "extensions.base.base_pb_desc"

local extensions_base_base_pb = {}

---@class extensions_base_base_pb.BaseMessage
---@field field string

---@class extensions_base_base_pb.MessageSetWireFormatMessage

---@type fun():extensions_base_base_pb.BaseMessage @New a '.goproto.protoc.extension.base.BaseMessage'
extensions_base_base_pb.BaseMessage = protobuf_reflect.Message(extensions_base_base_pb_desc.message_type[1])

---@type fun():extensions_base_base_pb.MessageSetWireFormatMessage @New a '.goproto.protoc.extension.base.MessageSetWireFormatMessage'
extensions_base_base_pb.MessageSetWireFormatMessage = protobuf_reflect.Message(extensions_base_base_pb_desc.message_type[2])


return extensions_base_base_pb
